/*
THIS IS A GENERATED/BUNDLED FILE
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, { default: () => ReviewPlugin });
module.exports = __toCommonJS(main_exports);

// Minimal shared settings for review
var DEFAULT_SETTINGS = {
  reviewSettings: { initialEase: 2.5, easyBonus: 1.3, intervalModifier: 1 },
  flashcardWidth: 800,
  flashcardHeight: 400,
  flashcardsDirectory: ".flashcards",
  activeDeck: "words.json"
};

// src/vocabulary/database.ts
var VocabularyDatabase = class {
  constructor(app, flashcardPath) {
    this.words = /* @__PURE__ */ new Map();
    this.app = app;
    this.flashcardPath = flashcardPath;
  }
  async load() {
    try {
      const adapter = this.app.vault.adapter;
      if (await adapter.exists(this.flashcardPath)) {
        const data = await adapter.read(this.flashcardPath);
        const entries = JSON.parse(data);
        this.words.clear();
        entries.forEach((entry) => {
          this.words.set(entry.id, entry);
        });
      }
    } catch (error) {
      console.error("Failed to load vocabulary database:", error);
    }
  }
  async save() {
    try {
      const adapter = this.app.vault.adapter;
      const dir = this.flashcardPath.substring(0, this.flashcardPath.lastIndexOf("/"));
      if (dir && !await adapter.exists(dir)) {
        await adapter.mkdir(dir);
      }
      const entries = Array.from(this.words.values());
      await adapter.write(this.flashcardPath, JSON.stringify(entries, null, 2));
    } catch (error) {
      console.error("Failed to save vocabulary database:", error);
    }
  }
  addWord(front, back, phonetic, source) {
    const id = `${front}-${Date.now()}`;
    const now = Date.now();
    const entry = {
      id,
      front,
      back,
      phonetic,
      source,
      timestamp: now,
      due: now,
      interval: 1,
      ease: 2.5,
      reviews: 0,
      lapses: 0,
      lastReview: 0,
      note: ""
    };
    this.words.set(id, entry);
    this.save();
    return entry;
  }
  updateWord(id, updates) {
    const entry = this.words.get(id);
    if (!entry)
      return false;
    if (updates.front)
      entry.front = updates.front;
    if (updates.back !== void 0)
      entry.back = updates.back;
    if (updates.phonetic !== void 0)
      entry.phonetic = updates.phonetic;
    if (updates.note !== void 0)
      entry.note = updates.note;
    this.save();
    return true;
  }
  removeWord(id) {
    const deleted = this.words.delete(id);
    if (deleted) {
      this.save();
    }
    return deleted;
  }
  getWord(id) {
    return this.words.get(id);
  }
  getWordByText(text3) {
    return Array.from(this.words.values()).find((entry) => entry.front === text3);
  }
  getAllWords() {
    return Array.from(this.words.values());
  }
  getDueWords(limit = Infinity) {
    const now = Date.now();
    return Array.from(this.words.values()).filter((word) => word.due <= now).sort((a, b) => a.due - b.due).slice(0, limit);
  }
  getNewWords(limit = Infinity) {
    return Array.from(this.words.values()).filter((word) => word.reviews === 0).sort((a, b) => a.timestamp - b.timestamp).slice(0, limit);
  }
  /**
   * Update review status using SM-2 algorithm
   * @param id word ID
   * @param quality 0=again, 1=hard, 2=good, 3=easy
   */
  updateReview(id, quality) {
    const word = this.words.get(id);
    if (!word)
      return void 0;
    const updated = calculateReviewUpdate(word, quality);
    Object.assign(word, updated);
    this.save();
    return word;
  }
  /**
   * Search words by query string
   */
  searchWords(query) {
    const lowerQuery = query.toLowerCase();
    return Array.from(this.words.values()).filter(
      (word) => word.front.toLowerCase().includes(lowerQuery) || word.back.toLowerCase().includes(lowerQuery)
    );
  }
  /**
   * Get paginated words with sorting
   */
  getWordsPaginated(page = 1, pageSize = 20, sortBy = "date") {
    const allWords = Array.from(this.words.values());
    allWords.sort((a, b) => {
      switch (sortBy) {
        case "front":
        case "front":
          return (a.front || "").localeCompare(b.front || "");
        case "reviews":
          return b.reviews - a.reviews;
        case "nextReview":
          return a.due - b.due;
        case "date":
        default:
          return b.timestamp - a.timestamp;
      }
    });
    const total = allWords.length;
    const pages = Math.ceil(total / pageSize);
    const start = (page - 1) * pageSize;
    const words = allWords.slice(start, start + pageSize);
    return { words, total, pages };
  }
  /**
   * Get statistics by dictionary source
   */
  getStatsBySource() {
    const stats = {
      youdao: 0,
      longman: 0,
      zdic: 0,
      souyun: 0
    };
    Array.from(this.words.values()).forEach((word) => {
      stats[word.source] = (stats[word.source] || 0) + 1;
    });
    return stats;
  }
  /**
   * Get recent activity statistics
   */
  getRecentActivity(days = 7) {
    const now = Date.now();
    const cutoff = now - days * 24 * 60 * 60 * 1e3;
    const words = Array.from(this.words.values());
    return {
      added: words.filter((w) => w.timestamp >= cutoff).length,
      reviewed: words.filter((w) => w.lastReview >= cutoff).length,
      mastered: words.filter(
        (w) => w.lastReview >= cutoff && w.interval >= 21
      ).length
    };
  }
  /**
   * Get overall statistics
   */
  getStats() {
    const words = Array.from(this.words.values());
    const now = Date.now();
    return {
      total: words.length,
      new: words.filter((w) => w.reviews === 0).length,
      due: words.filter((w) => w.due <= now).length,
      learning: words.filter((w) => w.reviews > 0 && w.interval < 21).length,
      mastered: words.filter((w) => w.interval >= 21).length
    };
  }
};
function calculateReviewUpdate(entry, quality) {
  const now = Date.now();
  const newReviews = entry.reviews + 1;
  let newLapses = entry.lapses;
  if (quality < 3) {
    newLapses++;
  }
  let newInterval;
  let newEase = entry.ease;
  if (quality < 2) {
    newInterval = 1;
  } else {
    newEase = newEase + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02));
    newEase = Math.max(1.3, newEase);
    if (newReviews === 1) {
      newInterval = 1;
    } else if (newReviews === 2) {
      newInterval = 6;
    } else {
      newInterval = Math.round(entry.interval * newEase);
    }
  }
  return {
    lastReview: now,
    reviews: newReviews,
    lapses: newLapses,
    interval: newInterval,
    ease: newEase,
    due: now + newInterval * 24 * 60 * 60 * 1e3
  };
}

// src/vocabulary/review-setup-modal.ts
var import_obsidian9 = require("obsidian");

// src/vocabulary/review-modal.ts
var import_obsidian7 = require("obsidian");
var EditWordModal = class extends import_obsidian7.Modal {
  constructor(app, database, word, onSave) {
    super(app);
    this.database = database;
    this.word = word;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Edit Word" });
    new import_obsidian7.Setting(contentEl).setName("Front (Word)").addText((text) => text.setValue(this.word.front).onChange((v) => this.word.front = v));
    new import_obsidian7.Setting(contentEl).setName("Back (Definition)").addTextArea((text) => text.setValue(this.word.back).onChange((v) => this.word.back = v));
    new import_obsidian7.Setting(contentEl).setName("Note").addTextArea((text) => text.setValue(this.word.note || "").onChange((v) => this.word.note = v));
    new import_obsidian7.Setting(contentEl).addButton((btn) => btn.setButtonText("Save").setCta().onClick(() => {
      this.database.updateWord(this.word.id, {
        front: this.word.front,
        back: this.word.back,
        note: this.word.note
      });
      this.onSave();
      this.close();
    })).addButton((btn) => btn.setButtonText("Cancel").onClick(() => this.close()));
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ReviewModal = class extends import_obsidian7.Modal {
  constructor(app, database, plugin, words = [], file) {
    super(app);
    this.currentIndex = 0;
    this.showingAnswer = false;
    // Resize state
    this.isResizing = false;
    this.startX = 0;
    this.startY = 0;
    this.startWidth = 0;
    this.startHeight = 0;
    // Drag state
    this.isDragging = false;
    this.dragStartX = 0;
    this.dragStartY = 0;
    this.initialLeft = 0;
    this.initialTop = 0;
    this.database = database;
    this.words = words;
    this.file = file;
    this.plugin = plugin;
    this.component = new import_obsidian7.Component();
  }
  async onOpen() {
    this.component.load();
    const { contentEl, modalEl } = this;
    const resizeHandle = modalEl.createDiv({ cls: "modal-resize-handle" });
    resizeHandle.addEventListener("mousedown", (e) => {
      if (this.isDragging)
        return;
      this.isResizing = true;
      this.startX = e.clientX;
      this.startY = e.clientY;
      this.startWidth = modalEl.offsetWidth;
      this.startHeight = modalEl.offsetHeight;
      e.preventDefault();
      e.stopPropagation();
    });
    this.onMouseMove = (e) => {
      if (!this.isResizing)
        return;
      const deltaX = e.clientX - this.startX;
      const deltaY = e.clientY - this.startY;
      modalEl.style.width = `${this.startWidth + deltaX}px`;
      modalEl.style.height = `${this.startHeight + deltaY}px`;
    };
    this.onMouseUp = () => {
      this.isResizing = false;
    };
    this.onDragMove = (e) => {
      if (!this.isDragging)
        return;
      const deltaX = e.clientX - this.dragStartX;
      const deltaY = e.clientY - this.dragStartY;
      modalEl.style.left = `${this.initialLeft + deltaX}px`;
      modalEl.style.top = `${this.initialTop + deltaY}px`;
    };
    this.onDragUp = () => {
      this.isDragging = false;
    };
    contentEl.addEventListener("mousedown", (e) => {
      const target = e.target;
      if (target.closest(".review-header") && !target.closest(".review-actions") && !target.closest("button")) {
        this.isDragging = true;
        this.dragStartX = e.clientX;
        this.dragStartY = e.clientY;
        const rect = modalEl.getBoundingClientRect();
        this.initialLeft = rect.left;
        this.initialTop = rect.top;
        modalEl.style.margin = "0";
        modalEl.style.position = "fixed";
        modalEl.style.left = `${rect.left}px`;
        modalEl.style.top = `${rect.top}px`;
        e.preventDefault();
      }
    });
    document.addEventListener("mousemove", this.onMouseMove);
    document.addEventListener("mouseup", this.onMouseUp);
    document.addEventListener("mousemove", this.onDragMove);
    document.addEventListener("mouseup", this.onDragUp);
    if (this.words.length === 0) {
      const allWords = this.database.getAllWords();
      if (allWords.length > 0) {
        this.words = allWords.sort(() => 0.5 - Math.random()).slice(0, 20);
        new import_obsidian7.Notice("\u{1F3B2} No words due. Starting a random review session!");
      }
    }
    if (this.words.length === 0) {
      contentEl.createEl("h2", { text: "\u{1F389} All Done!" });
      contentEl.createEl("p", { text: "No words saved to review yet. Start collecting some!" });
      return;
    }
    this.renderCard();
  }
  onClose() {
    this.component.unload();
    this.contentEl.empty();
    if (this.onMouseMove)
      document.removeEventListener("mousemove", this.onMouseMove);
    if (this.onMouseUp)
      document.removeEventListener("mouseup", this.onMouseUp);
    if (this.onDragMove)
      document.removeEventListener("mousemove", this.onDragMove);
    if (this.onDragUp)
      document.removeEventListener("mouseup", this.onDragUp);
  }
  processFlashcardContent(content, wordToHighlight) {
    if (!content)
      return "";
    let processed = content.trim().replace(/\n{3,}/g, "\n\n").replace(/\\\[([\s\S]*?)\\\]/g, "$$$$$1$$$$").replace(/\\\(\s*([\s\S]*?)\s*\\\)/g, "$$$1$$").replace(/\$\s+([^$]+?)\s+\$/g, "$$$1$$");
    if (wordToHighlight) {
      const escapedWord = wordToHighlight.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const regex = new RegExp(`(?<![\\*\\[\\|])${escapedWord}(?![\\*\\]\\|])`, "gi");
      processed = processed.replace(regex, (match) => `<span class="review-highlight">${match}</span>`);
    }
    return processed;
  }
  async renderCard() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("review-modal-content");
    if (this.currentIndex >= this.words.length) {
      this.showCompletion();
      return;
    }
    const word = this.words[this.currentIndex];
    const header = this.contentEl.createDiv({ cls: "review-header" });
    header.createEl("span", { text: `Card ${this.currentIndex + 1} of ${this.words.length}`, cls: "review-progress" });
    const actionsWrapper = header.createDiv({ cls: "review-card-actions" });
    const editBtn = actionsWrapper.createEl("span", { text: "\u{270F}\uFE0F", cls: "review-action-icon", attr: { title: "Edit Card" } });
    editBtn.addEventListener("click", () => {
      new EditWordModal(this.app, this.database, word, () => this.renderCard()).open();
    });
    const deleteBtn = actionsWrapper.createEl("span", { text: "\u{1F5D1}\uFE0F", cls: "review-action-icon", attr: { title: "Delete Card" } });
    deleteBtn.addEventListener("click", () => {
      if (confirm(`Delete "${word.front}"?`)) {
        this.database.removeWord(word.id);
        new import_obsidian7.Notice("Card deleted");
        this.words.splice(this.currentIndex, 1);
        this.renderCard();
      }
    });

    const statsEl = header.createDiv({ cls: "review-badges" });
    if (word.reviews === 0) {
      statsEl.createSpan({ text: "NEW", cls: "badge badge-new" });
    } else {
      statsEl.createSpan({ text: `Review #${word.reviews}`, cls: "badge badge-review" });
    }
    const cardContainer = this.contentEl.createDiv({ cls: "review-card-container" });
    const card = cardContainer.createDiv({ cls: `flashcard ${this.showingAnswer ? "is-flipped" : ""}` });
    const cardWidth = this.plugin.settings.flashcardWidth || 800;
    const cardHeight = this.plugin.settings.flashcardHeight || 400;
    card.style.maxWidth = `${cardWidth}px`;
    card.style.height = `${cardHeight}px`;
    card.addEventListener("click", (e) => {
      if (e.target.closest("button") || e.target.closest("a") || window.getSelection().toString())
        return;
      this.showingAnswer = !this.showingAnswer;
      if (this.showingAnswer) {
        card.addClass("is-flipped");
      } else {
        card.removeClass("is-flipped");
      }
      this.renderControls();
    });
    const frontFace = card.createDiv({ cls: "flashcard-front" });
    const frontContent = frontFace.createDiv({ cls: "flashcard-content question-side" });
    const frontText = word.front.startsWith("#") ? word.front : `# ${word.front}`;
    const processedFront = this.processFlashcardContent(frontText);
    await import_obsidian7.MarkdownRenderer.render(this.app, processedFront, frontContent, "", this.component);
    if (word.phonetic) {
      frontContent.createEl("div", { text: word.phonetic, cls: "review-phonetic" });
    }
    const hint = frontFace.createDiv({ cls: "flashcard-hint" });
    hint.createSpan({ text: "\u{1F4A1} Tap to reveal answer" });
    const backFace = card.createDiv({ cls: "flashcard-back" });
    const backContent = backFace.createDiv({ cls: "flashcard-content answer-side" });
    const defSection = backContent.createDiv({ cls: "review-definition" });
    if (word.back && word.back.trim()) {
      const processedDef = this.processFlashcardContent(word.back, word.front);
      await import_obsidian7.MarkdownRenderer.render(this.app, processedDef, defSection, "", this.component);
    } else {
      defSection.createDiv({ text: "(No definition found)", cls: "review-def-line review-no-def" });
    }
    if (word.note && word.note.trim()) {
      const noteSection = backContent.createDiv({ cls: "review-note-section" });
      const processedNote = this.processFlashcardContent(word.note);
      await import_obsidian7.MarkdownRenderer.render(this.app, processedNote, noteSection, "", this.component);
    }
    const metaSection = backContent.createDiv({ cls: "review-metadata" });
    metaSection.createDiv({ text: `Source: ${word.source}`, cls: "review-source" });
    this.renderControls();
  }
  renderControls() {
    const existingControls = this.contentEl.querySelector(".review-controls-container");
    if (existingControls)
      existingControls.remove();
    const controlsContainer = this.contentEl.createDiv({ cls: "review-controls-container" });
    const navContainer = controlsContainer.createDiv({ cls: "review-navigation" });
    const prevBtn = navContainer.createEl("button", {
      cls: "review-nav-btn review-prev-btn",
      text: "\u2190 Previous"
    });
    if (this.currentIndex === 0) {
      prevBtn.disabled = true;
      prevBtn.addClass("is-disabled");
    } else {
      prevBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.currentIndex--;
        this.showingAnswer = false;
        this.renderCard();
      });
    }
    if (this.showingAnswer) {
      this.renderRatingButtons(controlsContainer);
    } else {
      const skipBtn = navContainer.createEl("button", {
        cls: "review-nav-btn review-skip-btn",
        text: "Skip \u2192"
      });
      skipBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.currentIndex++;
        this.showingAnswer = false;
        this.renderCard();
      });
    }
  }
  renderRatingButtons(container) {
    const buttonContainer = container.createDiv({ cls: "review-actions" });
    const buttons = [
      { emoji: "\u{1F630}", title: "\u5FD8\u8BB0", label: "Forgot", quality: 0, cls: "is-forget" },
      { emoji: "\u{1F61F}", title: "\u56F0\u96BE", label: "Hard", quality: 2, cls: "is-hard" },
      { emoji: "\u{1F60A}", title: "\u4E00\u822C", label: "Good", quality: 3, cls: "is-good" },
      { emoji: "\u{1F604}", title: "\u7B80\u5355", label: "Easy", quality: 5, cls: "is-easy" }
    ];
    buttons.forEach(({ emoji, title, label, quality, cls }) => {
      const btn = buttonContainer.createEl("button", { cls: `review-btn-new ${cls}` });
      const content = btn.createDiv({ cls: "btn-content" });
      content.createDiv({ text: `${emoji} ${title}`, cls: "btn-title" });
      content.createDiv({ text: label, cls: "btn-subtitle" });
      btn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.handleRating(quality);
      });
    });
  }
  async handleRating(quality) {
    const word = this.words[this.currentIndex];
    if (this.file) {
      let dbWord = this.database.getWordByText(word.front);
      if (!dbWord) {
        dbWord = this.database.addWord(word.front, word.back, word.phonetic, "file-review");
        new import_obsidian7.Notice(`Added "${word.front}" to Vocabulary List`);
      }
      this.database.updateReview(dbWord.id, quality);
    } else {
      this.database.updateReview(word.id, quality);
    }
    if (this.file && quality >= 3) {
      try {
        const content = await this.app.vault.read(this.file);
        const lines = content.split("\n");
        let modified = false;
        const escapedWord = word.front.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        const regex = new RegExp(`^-\\s*${escapedWord}[:\uFF1A]`);
        const newLines = lines.map((line) => {
          if (regex.test(line)) {
            modified = true;
            return line.replace(/^-\s*/, "- [x] ");
          }
          return line;
        });
        if (modified) {
          await this.app.vault.modify(this.file, newLines.join("\n"));
          new import_obsidian7.Notice(`Marked "${word.front}" as known`);
        }
      } catch (e) {
        console.error("Failed to update file", e);
      }
    }
    this.currentIndex++;
    this.showingAnswer = false;
    this.renderCard();
  }
  showCompletion() {
    this.contentEl.empty();
    this.contentEl.createEl("h2", { text: "\u{1F389} Review Complete!" });
    this.contentEl.createEl("p", { text: `You reviewed ${this.words.length} words.` });
    const stats = this.database.getStats();
    const statsEl = this.contentEl.createDiv({ cls: "review-stats-summary" });
    statsEl.createEl("p", { text: `Total words: ${stats.total}` });
    statsEl.createEl("p", { text: `Due today: ${stats.due}` });
    statsEl.createEl("p", { text: `Mastered: ${stats.mastered}` });
    new import_obsidian7.Setting(this.contentEl).addButton((btn) => btn.setButtonText("Close").setCta().onClick(() => this.close()));
  }
};

// src/utils/file-suggest-modal.ts
var import_obsidian8 = require("obsidian");
var FileSuggestModal = class extends import_obsidian8.FuzzySuggestModal {
  constructor(app, callback) {
    super(app);
    this.callback = callback;
  }
  getItems() {
    return this.app.vault.getFiles().filter((file) => file.extension === "md");
  }
  getItemText(item) {
    return item.path;
  }
  onChooseItem(item, evt) {
    this.callback(item);
  }
};

// src/utils/vocabulary-parser.ts
var VocabularyParser = class {
  parseMarkdown(content) {
    const lines = content.split("\n");
    const words = [];
    const now = Date.now();
    const regex = /^[-*+]\s*([^:：]+)[:：]\s*(.+)$/;
    lines.forEach((line, index2) => {
      if (line.trim().match(/^-\s*\[x\]/i)) {
        return;
      }
      const match = line.match(regex);
      if (match) {
        const front = match[1].trim();
        const back = match[2].trim();
        if (front && back) {
          words.push({
            id: `import-${now}-${index2}`,
            front,
            back,
            phonetic: "",
            source: "import",
            timestamp: now,
            due: now,
            interval: 0,
            ease: 2.5,
            reviews: 0,
            lapses: 0,
            lastReview: 0
          });
        }
      }
    });
    return words;
  }
};

// src/vocabulary/review-setup-modal.ts
var ReviewSetupModal = class extends import_obsidian9.Modal {
  constructor(app, database, history, plugin) {
    super(app);
    this.database = database;
    this.history = history;
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Start Review Session" });
    contentEl.createEl("p", { text: "Choose a source for your review session:" });
    const reviewLimit = this.plugin.settings.reviewSettings.maxReviewsPerDay;
    const newLimit = this.plugin.settings.reviewSettings.maxNewWordsPerDay;
    new import_obsidian9.Setting(contentEl).setName("Word List (SRS)").setDesc(`Review due words (Max ${reviewLimit}) and new words (Max ${newLimit})`).addButton((btn) => btn.setButtonText("Start Standard Review").setCta().onClick(() => {
      this.close();
      const dueWords = this.database.getDueWords(reviewLimit);
      const newWords = this.database.getNewWords(newLimit);
      const sessionWords = [...dueWords, ...newWords];
      if (sessionWords.length === 0) {
        new import_obsidian9.Notice("No words due for review!");
        return;
      }
      if (this.plugin.settings.reviewDisplayMode === "sidebar") {
        this.close();
        this.plugin.activateReviewSession(sessionWords);
      } else {
        new ReviewModal(this.app, this.database, this.plugin, sessionWords).open();
      }
    }));
    new import_obsidian9.Setting(contentEl).setName("Look up History").setDesc("Review your 50 most recently looked up words").addButton((btn) => btn.setButtonText("Review History").onClick(() => {
      this.startHistoryReview();
    }));
    new import_obsidian9.Setting(contentEl).setName("Markdown File").setDesc("Review words from a specific Markdown file (Format: - word: definition)").addButton((btn) => btn.setButtonText("Select File...").onClick(() => {
      this.startFileReview();
    }));
  }
  startHistoryReview() {
    const entries = this.history.getRecent(50);
    if (entries.length === 0) {
      new import_obsidian9.Notice("No history found");
      return;
    }
    const words = entries.map((e, index2) => ({
      id: `history-${e.timestamp}-${index2}`,
      front: e.front,
      back: e.back,
      phonetic: e.phonetic,
      source: "history",
      timestamp: e.timestamp,
      due: 0,
      interval: 0,
      ease: 2.5,
      reviews: 0,
      lapses: 0,
      lastReview: 0
    }));
    this.close();
    new ReviewModal(this.app, this.database, this.plugin, words).open();
  }
  startFileReview() {
    new FileSuggestModal(this.app, async (file) => {
      try {
        const content = await this.app.vault.read(file);
        const parser = new VocabularyParser();
        const words = parser.parseMarkdown(content);
        if (words.length === 0) {
          new import_obsidian9.Notice("No words found in file");
          return;
        }
        this.close();
        new ReviewModal(this.app, this.database, this.plugin, words, file).open();
      } catch (e) {
        console.error(e);
        new import_obsidian9.Notice("Failed to read file");
      }
    }).open();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/vocabulary/vocabulary-list-view.ts
var import_obsidian12 = require("obsidian");

// src/vocabulary/import-modal.ts
var import_obsidian11 = require("obsidian");
var ImportModal = class extends import_obsidian11.Modal {
  constructor(app, database, onImport) {
    super(app);
    this.database = database;
    this.onImport = onImport;
  }
  
  parseCSVRow(str) {
    const result = [];
    let curr = '';
    let inQuotes = false;
    for (let i = 0; i < str.length; i++) {
      const char = str[i];
      if (inQuotes) {
        if (char === '"') {
          if (str[i + 1] === '"') {
            curr += '"';
            i++; 
          } else {
            inQuotes = false;
          }
        } else {
          curr += char;
        }
      } else {
        if (char === '"') {
          inQuotes = true;
        } else if (char === ',') {
          result.push(curr.trim());
          curr = '';
        } else {
          curr += char;
        }
      }
    }
    result.push(curr.trim());
    return result;
  }

  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Import" });
    
    let importFormat = "json";
    
    new import_obsidian11.Setting(contentEl)
      .setName("Import Format")
      .setDesc("Select the format of the file you are importing.")
      .addDropdown(drop => {
        drop.addOption("json", "JSON Backup");
        drop.addOption("csv_standard", "Standard CSV/Excel (Front, Back, Note)");
        drop.addOption("csv_kindle", "Kindle CSV (Word, Definition, Context/Title)");
        drop.onChange(value => importFormat = value);
      });

    new import_obsidian11.Setting(contentEl).setName("Pick Local File").setDesc("Import from .json or .csv").addButton((btn) => btn.setButtonText("Select File...").onClick(() => {
      const input = document.createElement("input");
      input.type = "file";
      input.accept = ".txt,.json,.csv";
      input.onchange = (e) => {
        const file = e.target.files[0];
        const reader = new FileReader();
        reader.readAsText(file, "UTF-8");
        reader.onload = async (readerEvent) => {
          const content = readerEvent.target.result;
          let importedCards = [];
          
          if (importFormat === "json") {
            try {
              importedCards = JSON.parse(content);
            } catch (err) {
              new import_obsidian11.Notice("Invalid JSON file");
              return;
            }
          } else if (importFormat === "csv_standard" || importFormat === "csv_kindle") {
            const lines = content.split(/\r?\n/);
            if (lines.length > 0) {
              let headerMap = { front: 0, back: 1, note: 2, title: -1 };
              let startIndex = 0;
              const firstRow = this.parseCSVRow(lines[0]);
              const lowerFirstRow = firstRow.map(h => h.toLowerCase().trim());
              
              if (lowerFirstRow.some(h => ['front', 'forward', 'word', '\u67E5\u8BCD', '\u5355\u8BCD'].includes(h))) {
                 startIndex = 1;
                 if (importFormat === "csv_kindle") {
                   headerMap.front = lowerFirstRow.findIndex(h => ['word', '\u67E5\u8BCD', '\u5355\u8BCD'].some(k => h.includes(k)));
                   headerMap.back = lowerFirstRow.findIndex(h => ['definition', '\u89E3\u91CA', '\u91CA\u4E49'].some(k => h.includes(k)));
                   headerMap.note = lowerFirstRow.findIndex(h => ['usage', 'context', '\u539F\u6587', '\u53E5\u5B50'].some(k => h.includes(k)));
                   headerMap.title = lowerFirstRow.findIndex(h => ['title', 'book', '\u51FA\u5904', '\u4E66\u540D'].some(k => h.includes(k)));
                 } else {
                   headerMap.front = lowerFirstRow.findIndex(h => ['front', 'forward', 'word'].includes(h));
                   headerMap.back = lowerFirstRow.findIndex(h => ['back', 'backward', 'definition', 'meaning'].includes(h));
                   headerMap.note = lowerFirstRow.findIndex(h => ['note', 'context', 'usage', 'sentence'].includes(h));
                 }
                 
                 if (headerMap.front === -1) headerMap.front = 0;
                 if (headerMap.back === -1) headerMap.back = 1;
                 // Note may not exist, that's fine (-1 will be handled)
              }

              for (let i = startIndex; i < lines.length; i++) {
                 if (!lines[i].trim()) continue;
                 const cols = this.parseCSVRow(lines[i]);
                 const front = cols[headerMap.front] || '';
                 if (!front) continue;
                 
                 const back = cols[headerMap.back] || '';
                 let note = '';
                 
                 if (importFormat === "csv_kindle") {
                     if (headerMap.note !== -1 && cols[headerMap.note]) note += cols[headerMap.note] + '\n';
                     if (headerMap.title !== -1 && cols[headerMap.title]) note += `\u2014 *${cols[headerMap.title]}*`;
                 } else {
                     if (headerMap.note !== -1 && cols[headerMap.note]) note = cols[headerMap.note];
                 }

                 importedCards.push({
                    id: `import-${Date.now()}-${i}`,
                    front: front,
                    back: back,
                    note: note.trim(),
                    phonetic: "",
                    source: importFormat === "csv_kindle" ? "kindle-import" : "csv-import",
                    timestamp: Date.now(),
                    due: Date.now(),
                    interval: 0,
                    ease: 2.5,
                    reviews: 0,
                    lapses: 0,
                    lastReview: 0
                 });
              }
            }
          }

          if (importedCards.length > 0) {
            let count = 0;
            for (const word of importedCards) {
              this.database.words.set(word.id, word);
              count++;
            }
            await this.database.save();
            if (this.onImport)
              this.onImport();
            new import_obsidian11.Notice(`Imported ${count} words.`);
            this.close();
          } else {
            new import_obsidian11.Notice("No words could be imported from the file.");
          }
        };
      };
      input.click();
    }));
    
    new import_obsidian11.Setting(contentEl).setName("From Vault Markdown").setDesc("Format: - word: definition").addButton((btn) => btn.setButtonText("Choose Note").setCta().onClick(() => {
      new FileSuggestModal(this.app, (file) => {
        this.importFile(file);
        this.close();
      }).open();
    }));
  }
  async importFile(file) {
    try {
      const content = await this.app.vault.read(file);
      const parser = new VocabularyParser();
      const words = parser.parseMarkdown(content);
      if (words.length === 0) {
        new import_obsidian11.Notice("No words found in file");
        return;
      }
      let count = 0;
      for (const word of words) {
        this.database.addWord(word.front, word.back, word.phonetic, "import");
        count++;
      }
      new import_obsidian11.Notice(`Successfully imported ${count} words from ${file.basename}`);
      if (this.onImport)
        this.onImport();
    } catch (error) {
      console.error(error);
      new import_obsidian11.Notice("Failed to import file");
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/vocabulary/vocabulary-list-view.ts
var VocabularyListComponent = class {
  constructor(app, database) {
    this.containerEl = null;
    this.currentPage = 1;
    this.pageSize = 20;
    this.searchQuery = "";
    this.filterCategory = "all";
    this.sortBy = "date";
    this.sortDirection = "desc";
    this.searchTimeout = null;
    this.app = app;
    this.database = database;
    this.component = new import_obsidian12.Component();
  }
  mount(container) {
    this.containerEl = container;
    container.empty();
    container.addClass("vocabulary-list-container");
    this.component.load();
    this.render();
  }
  unload() {
    this.component.unload();
  }
  processContent(content) {
    if (!content)
      return "";
    return content.trim().replace(/\n{3,}/g, "\n\n").replace(/\\\[([\s\S]*?)\\\]/g, "$$$$$1$$$$").replace(/\\\(\s*([\s\S]*?)\s*\\\)/g, "$$$1$$").replace(/\$\s+([^$]+?)\s+\$/g, "$$$1$$");
  }
  async render() {
    if (!this.containerEl)
      return;
    const container = this.containerEl;
    container.empty();
    const header = container.createDiv({ cls: "vocab-header" });
    const stats = this.database.getStats();
    const topRow = header.createDiv({ cls: "vocab-top-row" });
    // Title removed
    const actionContainer = header.createDiv({ cls: "vocab-actions" });
    // Search moved to sort row
    // Import/Export buttons moved to Dashboard
    const statsDiv = container.createDiv({ cls: "vocab-stats" });
    statsDiv.createEl("span", { text: `\u{1F4DD} Due: ${stats.due}`, cls: "stat-item" });
    statsDiv.createEl("span", { text: `\u{1F195} New: ${stats.new}`, cls: "stat-item" });
    statsDiv.createEl("span", { text: `\u{1F4DA} Learning: ${stats.learning}`, cls: "stat-item" });
    statsDiv.createEl("span", { text: `\u2705 Mastered: ${stats.mastered}`, cls: "stat-item" });
    
    if (this.filterCategory !== "all") {
      const filterIndicator = container.createDiv({ cls: "vocab-filter-indicator" });
      const label = this.filterCategory.charAt(0).toUpperCase() + this.filterCategory.slice(1);
      filterIndicator.createSpan({ text: `Filtered by: ${label}` });
      const clearBtn = filterIndicator.createSpan({ text: " (Clear)", cls: "clear-filter-btn" });
      clearBtn.addEventListener("click", () => {
        this.filterCategory = "all";
        this.render();
      });
    }

    let words;
    let total;
    let pages;
    
    let sourceWords = this.database.getAllWords();
    if (this.filterCategory === "due") {
      const now = Date.now();
      sourceWords = sourceWords.filter(w => w.due <= now);
    } else if (this.filterCategory === "new") {
      sourceWords = sourceWords.filter(w => w.reviews === 0);
    } else if (this.filterCategory === "mastered") {
      sourceWords = sourceWords.filter(w => w.interval >= 21);
    }

    if (this.searchQuery) {
      const lowerQuery = this.searchQuery.toLowerCase();
      sourceWords = sourceWords.filter(w => 
        w.front.toLowerCase().includes(lowerQuery) || 
        w.back.toLowerCase().includes(lowerQuery)
      );
    }
    
    sourceWords.sort((a, b) => {
      let cmp = 0;
      switch (this.sortBy) {
        case "word": cmp = a.front.localeCompare(b.front); break;
        case "reviews": cmp = a.reviews - b.reviews; break;
        case "nextReview": cmp = a.due - b.due; break;
        default: cmp = a.timestamp - b.timestamp; break;
      }
      return this.sortDirection === "desc" ? -cmp : cmp;
    });

    total = sourceWords.length;
    pages = Math.ceil(total / this.pageSize);
    const start = (this.currentPage - 1) * this.pageSize;
    words = sourceWords.slice(start, start + this.pageSize);

    const sortDiv = container.createDiv({ cls: "vocab-sort", attr: { style: "display: flex; align-items: center; justify-content: space-between; margin-bottom: 15px; gap: 10px;" } });
    const sortLeft = sortDiv.createDiv({ attr: { style: "display: flex; align-items: center; gap: 8px;" } });
    sortLeft.createEl("span", { text: "Sort: ", attr: { style: "font-size: 0.9em; color: var(--text-muted);" } });
    const sortSelect = sortLeft.createEl("select");
    const sortOptions = [
      { value: "date", label: "Date Added" },
      { value: "word", label: "Word (A-Z)" },
      { value: "reviews", label: "Review Count" },
      { value: "nextReview", label: "Next Review" }
    ];
    sortOptions.forEach((opt) => {
      const option = sortSelect.createEl("option", {
        text: opt.label,
        value: opt.value
      });
      if (opt.value === this.sortBy) {
        option.selected = true;
      }
    });
    sortSelect.addEventListener("change", (e) => {
      this.sortBy = e.target.value;
      this.currentPage = 1;
      this.render();
    });
    
    const dirSelect = sortLeft.createEl("select", { attr: { style: "margin-left: 5px;" } });
    const dirOptions = [
      { value: "desc", label: "\u5012\u5E8F (Desc)" },
      { value: "asc", label: "\u987A\u5E8F (Asc)" }
    ];
    dirOptions.forEach((opt) => {
      const option = dirSelect.createEl("option", { text: opt.label, value: opt.value });
      if (opt.value === this.sortDirection) option.selected = true;
    });
    dirSelect.addEventListener("change", (e) => {
      this.sortDirection = e.target.value;
      this.currentPage = 1;
      this.render();
    });
    
    // Search Bar added here
    const searchContainer = sortDiv.createDiv({ cls: "vocab-search", attr: { style: "flex: 1; max-width: 300px;" } });
    const searchInput = searchContainer.createEl("input", {
      type: "search",
      placeholder: "Search words...",
      value: this.searchQuery,
      attr: { style: "width: 100%; height: 30px; margin: 0;" }
    });
    searchInput.addEventListener("input", (e) => {
      if (this.searchTimeout)
        window.clearTimeout(this.searchTimeout);
      this.searchTimeout = window.setTimeout(() => {
        this.searchQuery = e.target.value;
        this.currentPage = 1;
        this.render();
      }, 1000);
    });
    const tableContainer = container.createDiv({ cls: "vocab-table-container" });
    const table = tableContainer.createEl("table", { cls: "vocab-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    headerRow.createEl("th", { text: "Front" });
    headerRow.createEl("th", { text: "Back" });
    headerRow.createEl("th", { text: "Note" });
    headerRow.createEl("th", { text: "Actions" });
    const tbody = table.createEl("tbody");
    if (words.length === 0) {
      const emptyRow = tbody.createEl("tr");
      const emptyCell = emptyRow.createEl("td", {
        text: this.searchQuery ? "No words found" : "No words saved yet",
        attr: { colspan: "4" },
        cls: "empty-message"
      });
    } else {
      for (const word of words) {
        const row = tbody.createEl("tr");
        const wordCell = row.createEl("td", { cls: "word-cell" });
        // Only wrap in ** if it doesn't already have markdown bolding
        const wordText = (word.front.startsWith("**") && word.front.endsWith("**")) ? word.front : `**${word.front}**`;
        const processedFront = this.processContent(wordText);
        wordCell.empty();
        await import_obsidian12.MarkdownRenderer.render(this.app, processedFront, wordCell, "", this.component);
        if (word.phonetic) {
          const phoneticEl = wordCell.createDiv({ cls: "phonetic-container" });
          phoneticEl.createEl("span", { text: `/${word.phonetic}/`, cls: "phonetic" });
        }
        wordCell.addEventListener("dblclick", (e) => {
          e.preventDefault();
          wordCell.empty();
          const input = wordCell.createEl("input", { type: "text", value: word.front });
          input.style.width = "100%";
          input.focus();
          const save = () => {
            if (input.value && input.value !== word.front) {
              this.database.updateWord(word.id, { front: input.value });
              this.render();
            } else {
              this.render();
            }
          };
          input.addEventListener("blur", save);
          input.addEventListener("keydown", (k) => {
            if (k.key === "Enter")
              input.blur();
          });
        });
        const defCell = row.createEl("td", { cls: "definition-cell" });
        const defContentDiv = defCell.createDiv({ cls: "vocab-def-content" });
        defContentDiv.style.maxHeight = "150px";
        defContentDiv.style.overflowY = "auto";
        if (word.back) {
          const processedDef = this.processContent(word.back);
          defContentDiv.empty();
          await import_obsidian12.MarkdownRenderer.render(this.app, processedDef, defContentDiv, "", this.component);
        } else {
          defContentDiv.setText("(No definition)");
          defContentDiv.addClass("text-muted");
        }
        defCell.addEventListener("dblclick", (e) => {
          e.preventDefault();
          e.stopPropagation();
          defCell.empty();
          const textarea = defCell.createEl("textarea");
          textarea.value = word.back;
          textarea.style.width = "100%";
          textarea.style.minHeight = "100px";
          textarea.focus();
          const save = () => {
            if (textarea.value !== word.back) {
              this.database.updateWord(word.id, { back: textarea.value });
              this.render();
            } else {
              this.render();
            }
          };
          textarea.addEventListener("blur", save);
        });
        const noteCell = row.createEl("td", { cls: "note-cell" });
        const noteContentDiv = noteCell.createDiv({ cls: "vocab-note-content" });
        noteContentDiv.style.maxHeight = "150px";
        noteContentDiv.style.overflowY = "auto";
        if (word.note) {
          const processedNote = this.processContent(word.note);
          noteContentDiv.empty();
          await import_obsidian12.MarkdownRenderer.render(this.app, processedNote, noteContentDiv, "", this.component);
        } else {
          noteContentDiv.setText("(Add note)");
          noteContentDiv.addClass("text-muted");
        }
        noteCell.addEventListener("dblclick", (e) => {
          e.preventDefault();
          e.stopPropagation();
          noteCell.empty();
          const textarea = noteCell.createEl("textarea");
          textarea.value = word.note || "";
          textarea.style.width = "100%";
          textarea.style.minHeight = "100px";
          textarea.focus();
          const save = () => {
            if (textarea.value !== word.note) {
              this.database.updateWord(word.id, { note: textarea.value });
              this.render();
            } else {
              this.render();
            }
          };
          textarea.addEventListener("blur", save);
        });

        const actionsCell = row.createEl("td", { cls: "actions-cell" });
        const deleteBtn = actionsCell.createEl("button", { text: "\u{1F5D1}\uFE0F", cls: "delete-btn" });
        deleteBtn.addEventListener("click", () => {
          if (confirm(`Delete "${word.front}"?`)) {
            this.database.removeWord(word.id);
            new import_obsidian12.Notice(`Deleted "${word.front}"`);
            this.render();
          }
        });
      }
    }
    if (pages > 1) {
      const pagination = container.createDiv({ cls: "vocab-pagination" });
      const prevBtn = pagination.createEl("button", {
        text: "\u2190 Prev",
        cls: "pagination-btn"
      });
      prevBtn.disabled = this.currentPage === 1;
      prevBtn.addEventListener("click", () => {
        if (this.currentPage > 1) {
          this.currentPage--;
          this.render();
        }
      });
      pagination.createEl("span", {
        text: `Page ${this.currentPage} of ${pages}`,
        cls: "page-info"
      });
      const nextBtn = pagination.createEl("button", {
        text: "Next \u2192",
        cls: "pagination-btn"
      });
      nextBtn.disabled = this.currentPage === pages;
      nextBtn.addEventListener("click", () => {
        if (this.currentPage < pages) {
          this.currentPage++;
          this.render();
        }
      });
    }
  }
};

var NewDeckModal = class extends import_obsidian11.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Create New Deck" });
    
    const inputDiv = contentEl.createDiv({ attr: { style: "margin: 20px 0;" } });
    const input = inputDiv.createEl("input", { type: "text", placeholder: "Deck name (e.g. japanese)", attr: { style: "width: 100%;" } });
    
    const btnDiv = contentEl.createDiv({ attr: { style: "display: flex; justify-content: flex-end; gap: 10px;" } });
    const btn = btnDiv.createEl("button", { text: "Create", cls: "mod-cta" });
    
    const saveDeck = async () => {
      let name = input.value.trim().replace(/[^a-zA-Z0-9_\u4e00-\u9fa5]/g, "");
      if (!name) {
        new import_obsidian11.Notice("Invalid deck name.");
        return;
      }
      if (!name.endsWith(".json")) name += ".json";
      const newPath = `${this.plugin.settings.flashcardsDirectory}/${name}`;
      this.close();
      await this.plugin.switchDeck(newPath);
      new import_obsidian11.Notice(`Switched to deck: ${name}`);
    };
    
    btn.addEventListener("click", saveDeck);
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") saveDeck();
    });
    setTimeout(() => input.focus(), 100);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/vocabulary/vocabulary-stats-view.ts
var VocabularyStatsComponent = class {
  constructor(app, database, history, plugin) {
    this.containerEl = null;
    this.app = app;
    this.database = database;
    this.history = history;
    this.plugin = plugin;
  }
  mount(container) {
    this.containerEl = container;
    container.empty();
    container.addClass("vocabulary-stats-container");
    this.render();
  }
  get settings() {
    return this.plugin.settings;
  }
  async getAvailableDecks() {
    const adapter = this.app.vault.adapter;
    const dir = this.plugin.settings.flashcardsDirectory;
    const dirExists = await adapter.exists(dir);
    if (!dirExists) {
      await adapter.mkdir(dir);
      return [`${dir}/${this.plugin.settings.activeDeck}`];
    }
    const listed = await adapter.list(dir);
    const files = listed.files.filter(f => f.endsWith(".json"));
    if (files.length === 0) return [`${dir}/${this.plugin.settings.activeDeck}`];
    return files;
  }

  async render() {
    var _a5, _b, _c, _d;
    if (!this.containerEl)
      return;
    const container = this.containerEl;
    container.empty();
    // \u2500\u2500 Header Section \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
    const headerRow = container.createDiv({ attr: { style: "display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;" } });
    
    const leftActions = headerRow.createDiv({ attr: { style: "flex: 1; display: flex; align-items: center; gap: 8px;" } });
    
    const deckSelect = leftActions.createEl("select", { cls: "dropdown deck-selector" });
    const decks = await this.getAvailableDecks();
    decks.forEach(deckPath => {
       const optionName = deckPath.replace(this.plugin.settings.flashcardsDirectory + '/', '').replace('.json', '');
       const option = deckSelect.createEl("option", { text: optionName, value: deckPath });
       if (deckPath === this.database.flashcardPath) {
           option.selected = true;
       }
    });
    
    deckSelect.addEventListener("change", async (e) => {
       await this.plugin.switchDeck(e.target.value);
    });

    const newDeckBtn = leftActions.createEl("button", { text: "+", attr: { title: "New Deck", style: "padding: 4px 8px; font-weight: bold;" } });
    newDeckBtn.addEventListener("click", () => {
       new NewDeckModal(this.app, this.plugin).open();
    });
    
    const statsTitle = headerRow.createEl("h2", { text: "\u{1F4CA} Statistics", attr: { style: "margin: 0; flex: 2; text-align: center;" } });
    
    const toolbarActions = headerRow.createDiv({ cls: "mr-toolbar-actions", attr: { style: "flex: 1; display: flex; justify-content: flex-end; gap: 8px;" } });
    const importBtn = toolbarActions.createEl("button", { text: "\u{1F4E5} Import", cls: "mod-cta" });
    importBtn.addEventListener("click", () => {
      new ImportModal(this.app, this.database, () => this.render()).open();
    });
    
    const exportBtn = toolbarActions.createEl("button", { text: "\u{1F4E4} Export CSV" });
    exportBtn.addEventListener("click", () => {
      const cards = this.database.getAllWords();
      let csvContent = "Front,Back,Phonetic,Note,Source\n";
      cards.forEach(card => {
        const escapeCSV = (str) => {
          if (!str) return '""';
          return '"' + str.replace(/"/g, '""') + '"';
        };
        const row = [card.front, card.back, card.phonetic, card.note, card.source].map(escapeCSV).join(",");
        csvContent += row + "\n";
      });

      const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `vocabulary_export_${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}.csv`;
      a.click();
      URL.revokeObjectURL(url);
      new import_obsidian13.Notice("Exported to CSV.");
    });

    const stats = this.database.getStats();
    const overviewDiv = container.createDiv({ cls: "mr-stats-overview" });
    this.createStatCard(overviewDiv, stats.total.toString(), "Total Words", "\u{1F4DA}", "all");
    this.createStatCard(overviewDiv, stats.due.toString(), "Due Today", "\u23F0", "due");
    this.createStatCard(overviewDiv, stats.new.toString(), "New Words", "\u{1F195}", "new");
    this.createStatCard(overviewDiv, stats.mastered.toString(), "Mastered", "\u2705", "mastered");
    const progressSection = container.createDiv({ cls: "mr-stats-section" });
    progressSection.createEl("h3", { text: "Learning Progress" });
    if (stats.total > 0) {
      const progressBarData = progressSection.createDiv({ cls: "mr-progress-bar-container" });
      const newPercent = stats.new / stats.total * 100;
      const learningPercent = stats.learning / stats.total * 100;
      const masteredPercent = stats.mastered / stats.total * 100;
      if (newPercent > 0) {
        const newBar = progressBarData.createDiv({
          cls: "mr-progress-bar mr-new-bar",
          attr: { style: `width: ${newPercent}%` }
        });
        newBar.createEl("span", { text: `New ${Math.round(newPercent)}%` });
      }
      if (learningPercent > 0) {
        const learningBar = progressBarData.createDiv({
          cls: "mr-progress-bar mr-learning-bar",
          attr: { style: `width: ${learningPercent}%` }
        });
        learningBar.createEl("span", { text: `Learning ${Math.round(learningPercent)}%` });
      }
      if (masteredPercent > 0) {
        const masteredBar = progressBarData.createDiv({
          cls: "mr-progress-bar mr-mastered-bar",
          attr: { style: `width: ${masteredPercent}%` }
        });
        masteredBar.createEl("span", { text: `Mastered ${Math.round(masteredPercent)}%` });
      }
      const legend = progressSection.createDiv({ cls: "mr-progress-legend" });
      legend.createEl("span", { text: `\u{1F195} New: ${stats.new} (${Math.round(newPercent)}%)`, cls: "mr-legend-item" });
      legend.createEl("span", { text: `\u{1F4DA} Learning: ${stats.learning} (${Math.round(learningPercent)}%)`, cls: "mr-legend-item" });
      legend.createEl("span", { text: `\u2705 Mastered: ${stats.mastered} (${Math.round(masteredPercent)}%)`, cls: "mr-legend-item" });
    } else {
      progressSection.createEl("p", { text: "No words saved yet. Start collecting words to see your progress!" });
    }
    const sourceSection = container.createDiv({ cls: "mr-stats-section" });
    sourceSection.createEl("h3", { text: "By Source" });
    const sourceStats = this.database.getStatsBySource();
    const sourceList = sourceSection.createEl("ul", { cls: "mr-source-list" });
    const sourceNames = {
      youdao: "\u{1F4D5} Youdao",
      longman: "\u{1F4D4} Longman",
      zdic: "\u{1F4D9} Zdic",
      souyun: "\u{1F4DA} Sou-Yun"
    };
    Object.entries(sourceStats).forEach(([source, count]) => {
      if (count > 0) {
        const item = sourceList.createEl("li");
        item.createEl("span", { text: sourceNames[source] || source, cls: "mr-source-name" });
        item.createEl("span", { text: count.toString(), cls: "mr-source-count" });
      }
    });
    if (Object.values(sourceStats).every((c) => c === 0)) {
      sourceSection.createEl("p", { text: "No words saved yet" });
    }
    const activitySection = container.createDiv({ cls: "mr-stats-section" });
    activitySection.createEl("h3", { text: "Recent Activity (Last 7 Days)" });
    const activity = this.database.getRecentActivity(7);
    const activityList = activitySection.createEl("ul", { cls: "mr-activity-list" });
    activityList.createEl("li", { text: `\u2795 Added: ${activity.added} words` });
    activityList.createEl("li", { text: `\u{1F4D6} Reviewed: ${activity.reviewed} times` });
    activityList.createEl("li", { text: `\u{1F393} Mastered: ${activity.mastered} words` });
  }
  createStatCard(container, value, label, icon, type) {
    const card = container.createDiv({ cls: "mr-stat-card" });
    card.createEl("div", { text: icon, cls: "mr-stat-icon" });
    card.createEl("h4", { text: value, cls: "mr-stat-value" });
    card.createEl("p", { text: label, cls: "mr-stat-label" });
    if (this.onCardClick) {
      card.addEventListener("click", () => this.onCardClick(type));
    }
  }
};

// src/vocabulary/review-setup-view.ts
var import_obsidian13 = require("obsidian");
var ReviewSetupComponent = class {
  constructor(app, database, history, plugin) {
    this.containerEl = null;
    this.app = app;
    this.database = database;
    this.history = history;
    this.plugin = plugin;
  }
  get settings() {
    return this.plugin.settings;
  }
  mount(container) {
    this.containerEl = container;
    container.empty();
    container.addClass("review-setup-container");
    this.render();
  }
  render() {
    var _a5, _b, _c, _d;
    if (!this.containerEl)
      return;
    const container = this.containerEl;
    container.empty();
    container.createEl("h2", { text: "Start Review Session" });
    container.createEl("p", { text: "Choose a source for your review session:" });
    const reviewLimit = (_b = (_a5 = this.settings.reviewSettings) == null ? void 0 : _a5.maxReviewsPerDay) != null ? _b : 20;
    const newLimit = (_d = (_c = this.settings.reviewSettings) == null ? void 0 : _c.maxNewWordsPerDay) != null ? _d : 5;
    new import_obsidian13.Setting(container).setName("Word List").addButton((btn) => btn.setButtonText("SRS Review").setCta().onClick(() => {
      const dueWords = this.database.getDueWords(reviewLimit);
      const newWords = this.database.getNewWords(newLimit);
      const sessionWords = [...dueWords, ...newWords];
      if (sessionWords.length === 0) {
        new import_obsidian13.Notice("No words due for review!");
        return;
      }
      if (this.plugin.settings.reviewDisplayMode === "sidebar") {
        this.plugin.activateReviewSession(sessionWords);
      } else {
        new ReviewModal(this.app, this.database, this.plugin, sessionWords).open();
      }
    }));
    if (this.history) {
      new import_obsidian13.Setting(container).setName("Look up History").addButton((btn) => btn.setButtonText("Review History").onClick(() => {
        this.startHistoryReview();
      }));
    }
    new import_obsidian13.Setting(container).setName("Markdown File").addButton((btn) => btn.setButtonText("Select File...").onClick(() => {
      this.startHistoryReview(); // Wait, this look like it was a bug in the original code? Or it should call startFileReview?
      // Actually the original code had startFileReview() at 1261.
      this.startFileReview();
    }));
  }
  startHistoryReview() {
    const entries = this.history.getRecent(50);
    if (entries.length === 0) {
      new import_obsidian13.Notice("No history found");
      return;
    }
    const words = entries.map((e, index2) => ({
      id: `history-${e.timestamp}-${index2}`,
      front: e.front,
      back: e.back,
      phonetic: e.phonetic,
      source: "history",
      timestamp: e.timestamp,
      due: 0,
      interval: 0,
      ease: 2.5,
      reviews: 0,
      lapses: 0,
      lastReview: 0
    }));
    if (this.plugin.settings.reviewDisplayMode === "sidebar") {
      this.plugin.activateReviewSession(words);
    } else {
      new ReviewModal(this.app, this.database, this.plugin, words).open();
    }
  }
  startFileReview() {
    new FileSuggestModal(this.app, async (file) => {
      try {
        const content = await this.app.vault.read(file);
        const parser = new VocabularyParser();
        const words = parser.parseMarkdown(content);
        if (words.length === 0) {
          new import_obsidian13.Notice("No words found in file");
          return;
        }
        if (this.plugin.settings.reviewDisplayMode === "sidebar") {
          this.plugin.activateReviewSession(words);
        } else {
          new ReviewModal(this.app, this.database, this.plugin, words, file).open();
        }
      } catch (e) {
        console.error(e);
        new import_obsidian13.Notice("Failed to read file");
      }
    }).open();
  }
};

// ── Review Sidebar View ───────────────────────────────────────────
var import_obsidian_rv = require("obsidian");
class ReviewSidebarSession {
  constructor(app, database, plugin, words, containerEl) {
    this.app = app;
    this.database = database;
    this.plugin = plugin;
    this.words = words;
    this.contentEl = containerEl;
    this.currentIndex = 0;
    this.showingAnswer = false;
    this.component = new import_obsidian7.Component();
  }
  render() {
    this.component.load();
    this.renderCard();
  }
  processFlashcardContent(content, wordToHighlight) {
    if (!content) return "";
    let processed = content.trim().replace(/\n{3,}/g, "\n\n").replace(/\\\[([\s\S]*?)\\\]/g, "$$$$$1$$$$").replace(/\\\(\s*([\s\S]*?)\s*\\\)/g, "$$$1$$").replace(/\$\s+([^$]+?)\s+\$/g, "$$$1$$");
    if (wordToHighlight) {
      const escapedWord = wordToHighlight.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const regex = new RegExp(`(?<![\\*\\[\\|])${escapedWord}(?![\\*\\]\\|])`, "gi");
      processed = processed.replace(regex, (match) => `<span class="review-highlight">${match}</span>`);
    }
    return processed;
  }
  async renderCard() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("review-modal-content");
    if (this.currentIndex >= this.words.length) {
      this.showCompletion();
      return;
    }
    const word = this.words[this.currentIndex];
    const header = this.contentEl.createDiv({ cls: "review-header" });
    header.createEl("span", { text: `Card ${this.currentIndex + 1} of ${this.words.length}`, cls: "review-progress" });
    const actionsWrapper = header.createDiv({ cls: "review-card-actions" });
    const editBtn = actionsWrapper.createEl("span", { text: "\u{270F}\uFE0F", cls: "review-action-icon", attr: { title: "Edit Card" } });
    editBtn.addEventListener("click", () => {
      new EditWordModal(this.app, this.database, word, () => this.renderCard()).open();
    });
    const deleteBtn = actionsWrapper.createEl("span", { text: "\u{1F5D1}\uFE0F", cls: "review-action-icon", attr: { title: "Delete Card" } });
    deleteBtn.addEventListener("click", () => {
      if (confirm(`Delete "${word.front}"?`)) {
        this.database.removeWord(word.id);
        new import_obsidian7.Notice("Card deleted");
        this.words.splice(this.currentIndex, 1);
        this.renderCard();
      }
    });

    const statsEl = header.createDiv({ cls: "review-badges" });
    if (word.reviews === 0) {
      statsEl.createSpan({ text: "NEW", cls: "badge badge-new" });
    } else {
      statsEl.createSpan({ text: `Review #${word.reviews}`, cls: "badge badge-review" });
    }
    const cardContainer = this.contentEl.createDiv({ cls: "review-card-container" });
    const card = cardContainer.createDiv({ cls: `flashcard ${this.showingAnswer ? "is-flipped" : ""}` });
    card.addEventListener("click", (e) => {
      if (e.target.closest("button") || e.target.closest("a") || window.getSelection().toString()) return;
      this.showingAnswer = !this.showingAnswer;
      if (this.showingAnswer) card.addClass("is-flipped");
      else card.removeClass("is-flipped");
      this.renderControls();
    });
    const frontFace = card.createDiv({ cls: "flashcard-front" });
    const frontContent = frontFace.createDiv({ cls: "flashcard-content question-side" });
    const frontText = word.front.startsWith("#") ? word.front : `# ${word.front}`;
    const processedFront = this.processFlashcardContent(frontText);
    await import_obsidian7.MarkdownRenderer.render(this.app, processedFront, frontContent, "", this.component);
    if (word.phonetic) frontContent.createEl("div", { text: word.phonetic, cls: "review-phonetic" });
    const hint = frontFace.createDiv({ cls: "flashcard-hint" });
    hint.createSpan({ text: this.showingAnswer ? "" : "\u{1F4A1} Tap to reveal answer" });
    const backFace = card.createDiv({ cls: "flashcard-back" });
    const backContent = backFace.createDiv({ cls: "flashcard-content answer-side" });
    const defSection = backContent.createDiv({ cls: "review-definition" });
    if (word.back && word.back.trim()) {
      const processedDef = this.processFlashcardContent(word.back, word.front);
      await import_obsidian7.MarkdownRenderer.render(this.app, processedDef, defSection, "", this.component);
    } else {
      defSection.createDiv({ text: "(No definition found)", cls: "review-def-line review-no-def" });
    }
    if (word.note && word.note.trim()) {
      const noteSection = backContent.createDiv({ cls: "review-note-section" });
      const processedNote = this.processFlashcardContent(word.note);
      await import_obsidian7.MarkdownRenderer.render(this.app, processedNote, noteSection, "", this.component);
    }
    const metaSection = backContent.createDiv({ cls: "review-metadata" });
    metaSection.createDiv({ text: `Source: ${word.source}`, cls: "review-source" });
    this.renderControls();
  }
  renderControls() {
    const existingControls = this.contentEl.querySelector(".review-controls-container");
    if (existingControls) existingControls.remove();
    const controlsContainer = this.contentEl.createDiv({ cls: "review-controls-container" });
    const navContainer = controlsContainer.createDiv({ cls: "review-navigation" });
    const prevBtn = navContainer.createEl("button", { cls: "review-nav-btn review-prev-btn", text: "\u2190 Previous" });
    if (this.currentIndex === 0) {
      prevBtn.disabled = true;
      prevBtn.addClass("is-disabled");
    } else {
      prevBtn.addEventListener("click", (e) => { e.stopPropagation(); this.currentIndex--; this.showingAnswer = false; this.renderCard(); });
    }
    if (this.showingAnswer) {
      this.renderRatingButtons(controlsContainer);
    } else {
      const skipBtn = navContainer.createEl("button", { cls: "review-nav-btn review-skip-btn", text: "Skip \u2192" });
      skipBtn.addEventListener("click", (e) => { e.stopPropagation(); this.currentIndex++; this.showingAnswer = false; this.renderCard(); });
    }
  }
  renderRatingButtons(container) {
    const buttonContainer = container.createDiv({ cls: "review-actions" });
    const buttons = [
      { emoji: "\u{1F630}", title: "\u5FD8\u8BB0", label: "Forgot", quality: 0, cls: "is-forget" },
      { emoji: "\u{1F61F}", title: "\u56F0\u96BE", label: "Hard", quality: 2, cls: "is-hard" },
      { emoji: "\u{1F60A}", title: "\u4E00\u822C", label: "Good", quality: 3, cls: "is-good" },
      { emoji: "\u{1F604}", title: "\u7B80\u5355", label: "Easy", quality: 5, cls: "is-easy" }
    ];
    buttons.forEach(({ emoji, title, label, quality, cls }) => {
      const btn = buttonContainer.createEl("button", { cls: `review-btn-new ${cls}` });
      const content = btn.createDiv({ cls: "btn-content" });
      content.createDiv({ text: `${emoji} ${title}`, cls: "btn-title" });
      content.createDiv({ text: label, cls: "btn-subtitle" });
      btn.addEventListener("click", (e) => { e.stopPropagation(); this.handleRating(quality); });
    });
  }
  async handleRating(quality) {
    const word = this.words[this.currentIndex];
    this.database.updateReview(word.id, quality);
    this.currentIndex++;
    this.showingAnswer = false;
    this.renderCard();
  }
  showCompletion() {
    this.contentEl.empty();
    this.contentEl.createEl("h2", { text: "\u{1F389} Review Complete!" });
    this.contentEl.createEl("p", { text: `You reviewed ${this.words.length} words.` });
    const stats = this.database.getStats();
    const statsEl = this.contentEl.createDiv({ cls: "review-stats-summary" });
    statsEl.createEl("p", { text: `Total words: ${stats.total}` });
    statsEl.createEl("p", { text: `Due today: ${stats.due}` });
    statsEl.createEl("p", { text: `Mastered: ${stats.mastered}` });
    new import_obsidian7.Setting(this.contentEl).addButton((btn) => btn.setButtonText("Back to Sidebar").setCta().onClick(() => {
        const view = this.app.workspace.getLeavesOfType(REVIEW_VIEW_TYPE)[0]?.view;
        if (view instanceof ReviewSidebarView) view.switchTab("stats");
    }));
  }
}
var REVIEW_VIEW_TYPE = "word-review-view";
var ReviewSidebarView = class extends import_obsidian_rv.ItemView {
  constructor(leaf, settings, database, plugin) {
    super(leaf);
    this.activeTab = "stats";
    this.settings = settings;
    this.database = database;
    this.plugin = plugin;
    this.vocabListComponent = new VocabularyListComponent(this.app, this.database);
    this.vocabStatsComponent = new VocabularyStatsComponent(this.app, this.database, null, this.plugin);
    this.vocabStatsComponent.onCardClick = (type) => this.showFilteredList(type);
    this.reviewSetupComponent = new ReviewSetupComponent(this.app, this.database, null, this.plugin);
  }
  showFilteredList(type) {
    this.vocabListComponent.filterCategory = type;
    this.vocabListComponent.currentPage = 1;
    this.switchTab("list");
  }
  getViewType() { return REVIEW_VIEW_TYPE; }
  getDisplayText() { return "Word Review"; }
  getIcon() { return "brain"; }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("unified-view-container");
    this.renderTabs(container);
    this.contentContainer = container.createDiv({ cls: "unified-content-container" });
    this.switchTab(this.activeTab);
  }
  renderTabs(container) {
    const tabsContainer = container.createDiv({ cls: "unified-tabs-container" });
    const tabs = [
      { id: "stats",  label: "Stats",      icon: "bar-chart-2" },
      { id: "list",   label: "List",       icon: "list" },
      { id: "review", label: "Review",     icon: "play" }
    ];
    tabs.forEach((tab) => {
      const tabEl = tabsContainer.createDiv({ cls: `unified-tab ${this.activeTab === tab.id ? "active" : ""}` });
      tabEl.setText(tab.label);
      tabEl.dataset.tabId = tab.id;
      tabEl.addEventListener("click", () => {
        this.switchTab(tab.id);
        tabsContainer.querySelectorAll(".unified-tab").forEach((t) => t.removeClass("active"));
        tabEl.addClass("active");
      });
    });
  }
  switchTab(tabId, customWords = null) {
    this.activeTab = tabId;
    if (!this.contentContainer) return;

    this.contentContainer.removeClass("vocabulary-list-container");
    this.contentContainer.removeClass("vocabulary-stats-container");
    this.contentContainer.removeClass("review-setup-container");
    this.contentContainer.empty();

    switch (tabId) {
      case "list":   this.vocabListComponent.mount(this.contentContainer);   break;
      case "stats":  this.vocabStatsComponent.mount(this.contentContainer);  break;
      case "review": 
        this.renderReviewSession(this.contentContainer, customWords);
        break;
    }
  }

  async renderReviewSession(container, customWords = null) {
    container.empty();
    let words = customWords;
    
    if (!words) {
      const dueWords = this.database.getDueWords();
      const newWords = this.database.getNewWords();
      words = [...dueWords, ...newWords];
    }

    if (words.length === 0) {
      const allWords = this.database.getAllWords();
      if (allWords.length > 0) {
        words = allWords.sort(() => 0.5 - Math.random()).slice(0, 20);
        new import_obsidian7.Notice("\u{1F3B2} No words due. Starting a random review!");
      }
    }

    if (words.length === 0) {
      container.createEl("h3", { text: "\u{1F389} All Done!" });
      container.createEl("p", { text: "No words saved yet. Start collecting words to review!" });
      return;
    }

    const reviewComp = new ReviewSidebarSession(this.app, this.database, this.plugin, words, container);
    reviewComp.render();
  }
};

// ── Review Settings Tab ───────────────────────────────────────────
var import_obsidian_rs = require("obsidian");
var ReviewSettingTab = class extends import_obsidian_rs.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u5355\u8bcd\u590d\u4e60\u8bbe\u7f6e" });

    new import_obsidian_rs.Setting(containerEl).setName("Flashcards Folder").setDesc("Vault relative path to the folder containing flashcard JSON files").addText(
      (t) => t.setValue(this.plugin.settings.flashcardsDirectory)
        .setPlaceholder(".flashcards")
        .onChange(async (v) => { this.plugin.settings.flashcardsDirectory = v; await this.plugin.saveSettings(); })
    );

    // Display mode setting removed (forced to Sidebar)
  }
};

// ── ReviewPlugin ──────────────────────────────────────────────────
var import_obsidian_r = require("obsidian");
var ReviewPlugin = class extends import_obsidian_r.Plugin {
  async onload() {
    await this.loadSettings();
    if (!this.settings.flashcardsDirectory) this.settings.flashcardsDirectory = ".flashcards";
    if (!this.settings.activeDeck) this.settings.activeDeck = "words.json";
    
    const initPath = this.settings.flashcardsDirectory + "/" + this.settings.activeDeck;
    this.database = new VocabularyDatabase(this.app, initPath);
    await this.database.load();
    // Receive words added by my-query via CustomEvent
    this.registerDomEvent(document, "add-ai-to-review", (e) => {
      if (e.detail && e.detail.word && e.detail.content) {
        const { word, content } = e.detail;
        const entry = this.database.addWord(word, content, "", "ai");
        if (entry) {
          new import_obsidian_r.Notice(`\u2705 \u5df2\u6dfb\u52a0\u5230\u590d\u4e60\u961f\u5217: ${word}`);
          this.app.workspace.getLeavesOfType(REVIEW_VIEW_TYPE).forEach((leaf) => {
            if (leaf.view instanceof ReviewSidebarView) {
              leaf.view.vocabListComponent.render();
              leaf.view.vocabStatsComponent.render();
            }
          });
        }
        else       new import_obsidian_r.Notice(`\u274c \u6dfb\u52a0\u5931\u8d25: ${word}`);
      }
    });
    this.registerDomEvent(document, "collect-memory", (e) => {
      if (e.detail && e.detail.word) {
        this.database.addWord(e.detail.word, e.detail.back || e.detail.definition || "", e.detail.phonetic || "", e.detail.source || "manual");
        new import_obsidian_r.Notice("\u{1f9e0} \u5df2\u6dfb\u52a0\u5230\u8bb0\u5fc6\u5e93");
        this.app.workspace.getLeavesOfType(REVIEW_VIEW_TYPE).forEach((leaf) => {
          if (leaf.view instanceof ReviewSidebarView) {
            leaf.view.vocabListComponent.render();
          }
        });
      }
    });
    this.registerView(REVIEW_VIEW_TYPE, (leaf) => new ReviewSidebarView(leaf, this.settings, this.database, this));
    this.addRibbonIcon("brain", "Word Review", () => { this.activateView(); });
    this.addCommand({
      id: "start-vocabulary-review", name: "Start vocabulary review",
      callback: () => { this.activateReviewSession(); }
    });
    this.addSettingTab(new ReviewSettingTab(this.app, this));
    console.log("My Review plugin loaded");
  }
  onunload() { this.app.workspace.detachLeavesOfType(REVIEW_VIEW_TYPE); }
  async activateView() {
    var _a;
    const existing = this.app.workspace.getLeavesOfType(REVIEW_VIEW_TYPE);
    if (existing.length === 0)
      await ((_a = this.app.workspace.getRightLeaf(false)) == null ? void 0 : _a.setViewState({ type: REVIEW_VIEW_TYPE, active: true }));
    const leaves = this.app.workspace.getLeavesOfType(REVIEW_VIEW_TYPE);
    if (leaves.length > 0) this.app.workspace.revealLeaf(leaves[0]);
  }
  async activateReviewSession(words) {
    await this.activateView();
    const leaf = this.app.workspace.getLeavesOfType(REVIEW_VIEW_TYPE)[0];
    if (leaf && leaf.view instanceof ReviewSidebarView) {
      const tabsContainer = leaf.view.containerEl.querySelector(".unified-tabs-container");
      if (tabsContainer) {
        tabsContainer.querySelectorAll(".unified-tab").forEach((t) => {
          if (t.dataset.tabId === "review") t.addClass("active");
          else t.removeClass("active");
        });
      }
      leaf.view.switchTab("review", words);
    }
  }
  async switchDeck(newPath) {
    const parts = newPath.split('/');
    this.settings.activeDeck = parts[parts.length - 1];
    await this.saveSettings();
    this.database.flashcardPath = newPath;
    this.database.words.clear();
    await this.database.load();
    this.app.workspace.getLeavesOfType(REVIEW_VIEW_TYPE).forEach((leaf) => {
      if (leaf.view instanceof ReviewSidebarView) {
        if (leaf.view.vocabListComponent) {
          leaf.view.vocabListComponent.currentPage = 1;
          leaf.view.vocabListComponent.render();
        }
        if (leaf.view.vocabStatsComponent) leaf.view.vocabStatsComponent.render();
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() { await this.saveData(this.settings); }
};
