/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_EXTRACTION: () => VIEW_TYPE_EXTRACTION,
  default: () => CalloutExportPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  dailyNotesFolder: "sources/diarys/2026",
  readingSection: "## \u9605\u8BFB",
  logSection: "## \u65E5\u5FD7",
  dailyNoteTemplate: `# {{date}}

{{readingSection}}

{{content}}

{{logSection}}
`,
  calloutExportTemplate: "- {{time}} #note {{content}} ([[SourceNote]])",
  customRegexes: [
    {
      name: "Color Text",
      regex: `<font\\s+color=["']?(?:#[0-9a-fA-F]{3,6})["']?>(.*?)<\\/font>`,
      template: "- {{time}} #color {{content}} ([[SourceNote]])"
    },
    {
      name: "Highlight",
      regex: "==(.*?)==",
      template: "- {{time}} #highlight {{content}} ([[SourceNote]])"
    }
  ],
  comments: {},
  openAIApiKey: "",
  aiModel: "gpt-3.5-turbo",
  customAiPrompt: "Analyze the following note content and highlights. Organize them into a brief, structured summarization note.",
  flashcardsPath: ".flashcards/hinote.json",
  customServerUrl: "https://api.openai.com/v1/chat/completions",
  saveFlashcardsToMarkdown: false,
  conceptNotesFolder: "wiki/02-Concepts",
  aiProfiles: [],
  lastActiveProfileId: ""
};
var VIEW_TYPE_EXTRACTION = "extraction-view";

// ── ExtractionView ────────────────────────────────────────────────
var ExtractionView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentFilePath = null;
    this.plugin = plugin;
    // ── 批量导出状态 ──
    this.bulkMode = false;
    this.selectedEntries = new Set();
  }
  // Helper to get comments for current file
  getComments() {
    if (!this.currentFilePath) return {};
    return this.plugin.settings.comments[this.currentFilePath] || {};
  }
  getViewType() {
    return VIEW_TYPE_EXTRACTION;
  }
  getDisplayText() {
    return "Highlights";
  }
  getIcon() {
    return "star";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    this.container = container;
    const file = this.app.workspace.getActiveFile();
    if (file) this.currentFilePath = file.path;
    this.updateView();
  }
  async onClose() {
  }
  updateView() {
    const container = this.container;
    if (!container) return;
    container.empty();
    // Only one tab: Highlights
    this.renderHighlights(container);
  }

  // Helper to style highlights yellow
  applyHighlightStyles(container) {
    container.createEl("style", {
      text: `
                .extraction-content mark {
                    background-color: rgba(255, 255, 0, 0.4) !important;
                    color: var(--text-normal) !important;
                    padding: 0 2px;
                    border-radius: 2px;
                }
                .theme-dark .extraction-content mark {
                    background-color: rgba(255, 255, 0, 0.2) !important;
                    color: var(--text-normal) !important;
                }
            `
    });
  }

  // ── Get the first configured AI profile ──
  getActiveProfile() {
    const profiles = this.plugin.settings.aiProfiles;
    if (!profiles || profiles.length === 0) return null;
    const lastId = this.plugin.settings.lastActiveProfileId;
    return profiles.find((p) => p.id === lastId) || profiles[0];
  }

  // ── Generate Chinese AI annotation for a single highlight ──
  async generateAiAnnotation(entryContent) {
    const profile = this.getActiveProfile();
    if (!profile) {
      new import_obsidian.Notice("请先在设置中配置 AI Profile");
      return null;
    }
    if (!profile.apiKey) {
      new import_obsidian.Notice("AI Profile 缺少 API Key，请在设置中填写");
      return null;
    }
    const systemPrompt = "你是一名中文学术研究助手。请对划线内容进行解释，写成适合贴在旁边的边注，最好是子弹笔记形式列出要点，直接回答，不说废话。尽量控制在50字以内。";
    const userPrompt = `请为下面的划线内容生成精练边注，只说最关键的意思：\n\n${entryContent}`;
    const url = profile.url || "https://api.openai.com/v1/chat/completions";
    const response = await (0, import_obsidian.requestUrl)({
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${profile.apiKey}`
      },
      body: JSON.stringify({
        model: profile.model || "gpt-3.5-turbo",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt }
        ],
        max_tokens: 300
      })
    });
    if (response.status === 200) {
      const data = response.json;
      return this.polishAiAnnotation(data.choices[0].message.content.trim(), 50);
    }
    throw new Error(`API error ${response.status}: ${response.text}`);
  }

  // ── Generate Chinese AI annotation with full article context ──
  async generateAiAnnotationWithContext(entryContent, articleContent) {
    const profile = this.getActiveProfile();
    if (!profile) {
      new import_obsidian.Notice("请先在设置中配置 AI Profile");
      return null;
    }
    if (!profile.apiKey) {
      new import_obsidian.Notice("AI Profile 缺少 API Key，请在设置中填写");
      return null;
    }
    const systemPrompt = "你是一名中文学术研究助手。用户会提供文章原文和其中一段划线内容。请结合上下文，写成适合贴在旁边的精练边注：点出这句在全文中的关键含义或复述原句，只列要点。尽量控制在60字以内。";
    const userPrompt = `【文章原文】\n${articleContent}\n\n【划线内容】\n${entryContent}\n\n请结合上下文，为这段划线内容写一句精练边注：`;
    const url = profile.url || "https://api.openai.com/v1/chat/completions";
    const response = await (0, import_obsidian.requestUrl)({
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${profile.apiKey}`
      },
      body: JSON.stringify({
        model: profile.model || "gpt-3.5-turbo",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt }
        ],
        max_tokens: 400
      })
    });
    if (response.status === 200) {
      const data = response.json;
      return this.polishAiAnnotation(data.choices[0].message.content.trim(), 60);
    }
    throw new Error(`API error ${response.status}: ${response.text}`);
  }

  polishAiAnnotation(text, maxLength) {
    if (!text) return text;
    let cleaned = text.trim();
    cleaned = cleaned.replace(/^【?注释】?[：:\s-]*/u, "");
    cleaned = cleaned.replace(/^这段话(?:的意思)?是[：:\s]*/u, "");
    cleaned = cleaned.replace(/^划线部分(?:指|是在说)?[：:\s]*/u, "");
    cleaned = cleaned.replace(/\s+/g, " ");
    const firstSentenceMatch = cleaned.match(/^(.+?[。！？!?])(?:\s|$)/);
    if (firstSentenceMatch && firstSentenceMatch[1].length <= maxLength) {
      cleaned = firstSentenceMatch[1];
    }
    if (cleaned.length > maxLength) {
      cleaned = cleaned.slice(0, maxLength).replace(/[，、；：,.!！？\s]+$/u, "") + "。";
    }
    return cleaned;
  }
  mergeAnnotation(existingComment, newAnnotation) {
    const existing = (existingComment || "").trim();
    const incoming = (newAnnotation || "").trim();
    if (!existing) return incoming;
    if (!incoming) return existing;
    if (existing.includes(incoming)) return existing;
    return `${existing}

${incoming}`;
  }

  async renderHighlights(container) {
    this.applyHighlightStyles(container);
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view && !this.currentFilePath) {
      container.createEl("p", { text: "Open a markdown file to see highlights." });
      return;
    }
    let activeView = view;
    let content = "";
    if (activeView) {
      content = activeView.editor.getValue();
      if (activeView.file) this.currentFilePath = activeView.file.path;
    } else if (this.currentFilePath) {
      const file = this.app.vault.getAbstractFileByPath(this.currentFilePath);
      if (file instanceof import_obsidian.TFile) {
        content = await this.app.vault.read(file);
      }
    }
    if (!content) {
      container.createEl("p", { text: "No content found to analyze." });
      return;
    }
    const matches = this.plugin.extractMatches(content);
    const callouts = this.plugin.extractCallouts(content);
    const calloutEntries = callouts.map((c) => ({
      ruleName: "Note",
      template: "",
      content: c.text,
      fullMatch: `> ${c.text}`,
      index: c.index || 0
    }));
    let allEntries = [...matches];
    calloutEntries.forEach((c) => allEntries.push(c));
    allEntries.sort((a, b) => a.index - b.index);
    if (allEntries.length === 0) {
      container.createEl("div", {
        text: "No highlights found.",
        cls: "extraction-empty-state",
        attr: { style: "color: var(--text-muted); padding: 10px; text-align: center;" }
      });
      return;
    }
    // capture article content for context-aware annotation
    const articleContent = content;

    // ── 批量导出工具栏 ──────────────────────────────────────────
    const toolbar = container.createDiv({ cls: "bulk-toolbar" });
    toolbar.style.cssText = [
      "display:flex", "align-items:center", "gap:6px",
      "padding:6px 4px 8px", "border-bottom:1px solid var(--background-modifier-border)",
      "margin-bottom:8px", "flex-wrap:wrap"
    ].join(";");

    // 批量模式切换按钮
    const bulkToggleBtn = toolbar.createEl("button");
    bulkToggleBtn.textContent = this.bulkMode ? "✕ 退出批量" : "☑ 批量导出";
    bulkToggleBtn.style.cssText = [
      `background:${this.bulkMode ? "var(--interactive-accent)" : "var(--background-modifier-hover)"}`,
      `color:${this.bulkMode ? "var(--text-on-accent)" : "var(--text-normal)"}`,
      "border:none", "border-radius:5px", "padding:3px 10px",
      "cursor:pointer", "font-size:12px", "white-space:nowrap"
    ].join(";");
    bulkToggleBtn.title = this.bulkMode ? "退出批量导出模式" : "进入批量导出模式";
    bulkToggleBtn.onclick = () => {
      this.bulkMode = !this.bulkMode;
      this.selectedEntries.clear();
      this.updateView();
    };

    // 全选 / 取消全选 (仅批量模式)
    const selectAllBtn = toolbar.createEl("button");
    selectAllBtn.style.cssText = [
      "background:var(--background-modifier-hover)", "border:none",
      "border-radius:5px", "padding:3px 8px", "cursor:pointer",
      "font-size:12px", "white-space:nowrap",
      `display:${this.bulkMode ? "inline-block" : "none"}`
    ].join(";");
    const allKeys = allEntries.map(e => e.content.trim());
    const allSelected = this.bulkMode && allKeys.length > 0 && allKeys.every(k => this.selectedEntries.has(k));
    selectAllBtn.textContent = allSelected ? "☐ 取消全选" : "☑ 全选";
    selectAllBtn.title = allSelected ? "取消全选" : "全选所有条目";
    selectAllBtn.onclick = () => {
      if (allSelected) {
        this.selectedEntries.clear();
      } else {
        allEntries.forEach(e => this.selectedEntries.add(e.content.trim()));
      }
      this.updateView();
    };

    // 导出已选按钮 (仅批量模式)
    const exportSelectedBtn = toolbar.createEl("button");
    const selectedCount = this.selectedEntries.size;
    exportSelectedBtn.textContent = `⬆ 导出日记 (${selectedCount})`;
    exportSelectedBtn.style.cssText = [
      `background:${selectedCount > 0 ? "var(--interactive-accent)" : "var(--background-modifier-hover)"}`,
      `color:${selectedCount > 0 ? "var(--text-on-accent)" : "var(--text-muted)"}`,
      "border:none", "border-radius:5px", "padding:3px 10px",
      `cursor:${selectedCount > 0 ? "pointer" : "default"}`,
      "font-size:12px", "white-space:nowrap",
      `display:${this.bulkMode ? "inline-block" : "none"}`
    ].join(";");
    exportSelectedBtn.title = selectedCount > 0 ? `批量导出 ${selectedCount} 条到日记` : "请先勾选条目";
    exportSelectedBtn.onclick = async () => {
      if (selectedCount === 0) return;
      if (!this.currentFilePath) {
        new import_obsidian.Notice("无法确定来源文件"); return;
      }
      const sourceFile = this.app.vault.getAbstractFileByPath(this.currentFilePath);
      if (!(sourceFile instanceof import_obsidian.TFile)) {
        new import_obsidian.Notice("来源文件不存在"); return;
      }
      const toExport = allEntries.filter(e => this.selectedEntries.has(e.content.trim()));
      exportSelectedBtn.textContent = "导出中...";
      exportSelectedBtn.style.opacity = "0.6";
      let done = 0;
      for (const entry of toExport) {
        try {
          await this.plugin.exportSingleEntry(entry, sourceFile);
          done++;
        } catch (err) {
          console.error("[BulkExport] 导出失败:", err);
        }
      }
      this.selectedEntries.clear();
      this.bulkMode = false;
      new import_obsidian.Notice(`✅ 已批量导出 ${done} 条到日记`);
      this.updateView();
    };

    // ── 导出概念卡片按钮 (仅批量模式) ──
    const conceptCardBtn = toolbar.createEl("button");
    conceptCardBtn.textContent = `📝 导出卡片 (${selectedCount})`;
    conceptCardBtn.style.cssText = [
      `background:${selectedCount > 0 ? "#6c5ce7" : "var(--background-modifier-hover)"}`,
      `color:${selectedCount > 0 ? "#fff" : "var(--text-muted)"}`,
      "border:none", "border-radius:5px", "padding:3px 10px",
      `cursor:${selectedCount > 0 ? "pointer" : "default"}`,
      "font-size:12px", "white-space:nowrap",
      `display:${this.bulkMode ? "inline-block" : "none"}`
    ].join(";");
    conceptCardBtn.title = selectedCount > 0
      ? `将 ${selectedCount} 条高亮+注释导出为概念卡片笔记`
      : "请先勾选含 [[链接]] 或注释的条目";
    conceptCardBtn.onclick = async () => {
      if (selectedCount === 0) return;
      const toExport = allEntries.filter(e => this.selectedEntries.has(e.content.trim()));
      conceptCardBtn.textContent = "导出中...";
      conceptCardBtn.style.opacity = "0.6";
      const { created, skipped } = await this.exportAsConceptNotes(toExport);
      this.selectedEntries.clear();
      this.bulkMode = false;
      new import_obsidian.Notice(`✅ 概念卡片：已创建 ${created} 条，跳过 ${skipped} 条（已存在）`);
      this.updateView();
    };

    const listContainer = container.createDiv({ cls: "extraction-list" });
    allEntries.forEach((entry) => {
      const entryKey = entry.content.trim();
      const isChecked = this.selectedEntries.has(entryKey);
      const card = listContainer.createDiv({ cls: "extraction-card" });
      card.style.display = "flex";
      card.style.flexDirection = "column";
      card.style.padding = "10px";
      card.style.marginBottom = "12px";
      card.style.backgroundColor = isChecked && this.bulkMode
        ? "var(--background-modifier-hover)"
        : "var(--background-primary)";
      card.style.borderRadius = "8px";
      card.style.border = isChecked && this.bulkMode
        ? "1px solid var(--interactive-accent)"
        : "1px solid var(--background-modifier-border)";
      card.style.boxShadow = "0 2px 4px rgba(0,0,0,0.05)";
      card.style.transition = "border 0.15s, background 0.15s";

      // ── 批量模式复选框区域 ──
      if (this.bulkMode) {
        const checkRow = card.createDiv({ cls: "bulk-check-row" });
        checkRow.style.cssText = "display:flex;align-items:center;gap:6px;margin-bottom:6px;cursor:pointer";
        const checkbox = checkRow.createEl("input", { type: "checkbox" });
        checkbox.checked = isChecked;
        checkbox.style.cssText = "width:15px;height:15px;cursor:pointer;accent-color:var(--interactive-accent)";
        const checkLabel = checkRow.createEl("span", { text: isChecked ? "✓ 已选" : "点击选择" });
        checkLabel.style.cssText = "font-size:11px;color:var(--text-muted)";
        const toggleSelect = () => {
          if (this.selectedEntries.has(entryKey)) {
            this.selectedEntries.delete(entryKey);
          } else {
            this.selectedEntries.add(entryKey);
          }
          this.updateView();
        };
        checkbox.addEventListener("change", (e) => { e.stopPropagation(); toggleSelect(); });
        checkRow.addEventListener("click", (e) => { e.stopPropagation(); toggleSelect(); });
      }

      const cardHeader = card.createDiv({ cls: "card-header" });
      const exportIcon = cardHeader.createEl("span", { cls: "icon-btn" });
      (0, import_obsidian.setIcon)(exportIcon, "forward");
      exportIcon.title = "Export to Daily Note";
      exportIcon.onclick = async (e) => {
        e.stopPropagation();
        if (this.currentFilePath) {
          const file = this.app.vault.getAbstractFileByPath(this.currentFilePath);
          if (file instanceof import_obsidian.TFile) {
            await this.plugin.exportSingleEntry(entry, file);
          }
        }
      };

      // ── AI 注释按钮 ──
      const aiIcon = cardHeader.createEl("span", { cls: "icon-btn", title: "AI生成中文注释" });
      (0, import_obsidian.setIcon)(aiIcon, "bot");
      aiIcon.style.marginLeft = "6px";
      aiIcon.onclick = async (e) => {
        e.stopPropagation();
        aiIcon.style.opacity = "0.4";
        aiIcon.title = "生成中...";
        try {
          const annotation = await this.generateAiAnnotation(entry.content);
          if (!annotation) { aiIcon.style.opacity = "1"; aiIcon.title = "AI生成中文注释"; return; }
          const contentKey = entry.content.trim();
          if (!this.plugin.settings.comments[this.currentFilePath]) {
            this.plugin.settings.comments[this.currentFilePath] = {};
          }
          const existingComment = this.plugin.settings.comments[this.currentFilePath][contentKey] || "";
          const mergedAnnotation = this.mergeAnnotation(existingComment, annotation);
          this.plugin.settings.comments[this.currentFilePath][contentKey] = mergedAnnotation;
          // Also save to flashcards.json
          const flashcards = await this.loadFlashcardsData();
          const cardId = `${this.currentFilePath}-${contentKey}`;
          const existingIdx = flashcards.findIndex((f) => f.id === cardId);
          const newCard = {
            id: cardId,
            front: entry.content,
            back: mergedAnnotation,
            source: this.currentFilePath || "",
            timestamp: Date.now(),
            due: Date.now(),
            interval: 1,
            ease: 2.5,
            reviews: 0,
            lapses: 0,
            lastReview: Date.now()
          };
          if (existingIdx >= 0) {
            flashcards[existingIdx] = newCard;
          } else {
            flashcards.push(newCard);
          }
          await this.saveFlashcardsData(flashcards);
          await this.plugin.saveSettings();
          new import_obsidian.Notice("✅ AI注释已生成并保存");
          setTimeout(() => this.updateView(), 50);
        } catch (err) {
          console.error(err);
          new import_obsidian.Notice("AI注释生成失败: " + err.message);
          aiIcon.style.opacity = "1";
          aiIcon.title = "AI生成中文注释";
        }
      };

      // ── AI 注释按钮（结合文章）──
      const aiCtxIcon = cardHeader.createEl("span", { cls: "icon-btn", title: "结合文章AI注释" });
      (0, import_obsidian.setIcon)(aiCtxIcon, "book-open");
      aiCtxIcon.style.marginLeft = "6px";
      aiCtxIcon.onclick = async (e) => {
        e.stopPropagation();
        aiCtxIcon.style.opacity = "0.4";
        aiCtxIcon.title = "生成中...";
        try {
          const annotation = await this.generateAiAnnotationWithContext(entry.content, articleContent);
          if (!annotation) { aiCtxIcon.style.opacity = "1"; aiCtxIcon.title = "结合文章AI注释"; return; }
          const contentKey = entry.content.trim();
          if (!this.plugin.settings.comments[this.currentFilePath]) {
            this.plugin.settings.comments[this.currentFilePath] = {};
          }
          const existingComment = this.plugin.settings.comments[this.currentFilePath][contentKey] || "";
          const mergedAnnotation = this.mergeAnnotation(existingComment, annotation);
          this.plugin.settings.comments[this.currentFilePath][contentKey] = mergedAnnotation;
          const flashcards = await this.loadFlashcardsData();
          const cardId = `${this.currentFilePath}-${contentKey}`;
          const existingIdx = flashcards.findIndex((f) => f.id === cardId);
          const newCard = {
            id: cardId,
            front: entry.content,
            back: mergedAnnotation,
            source: this.currentFilePath || "",
            timestamp: Date.now(),
            due: Date.now(),
            interval: 1,
            ease: 2.5,
            reviews: 0,
            lapses: 0,
            lastReview: Date.now()
          };
          if (existingIdx >= 0) {
            flashcards[existingIdx] = newCard;
          } else {
            flashcards.push(newCard);
          }
          await this.saveFlashcardsData(flashcards);
          await this.plugin.saveSettings();
          new import_obsidian.Notice("✅ 文章上下文注释已生成并保存");
          setTimeout(() => this.updateView(), 50);
        } catch (err) {
          console.error(err);
          new import_obsidian.Notice("注释生成失败: " + err.message);
          aiCtxIcon.style.opacity = "1";
          aiCtxIcon.title = "结合文章AI注释";
        }
      };

      // ── Wiki 笔记快速生成按钮（仅单 [[链接]] 条目显示）──
      const soloWikiMatch = entry.content.trim().match(/^\[\[([^\[\]|]+?)(?:\|([^\]]*))?\]\]$/);
      if (soloWikiMatch) {
        const wikiName  = soloWikiMatch[1].trim();   // XXX
        const wikiAlias = soloWikiMatch[2]?.trim() || ""; // ABC（若有）
        const wikiIcon = cardHeader.createEl("span", { cls: "icon-btn", title: `生成 Wiki 笔记：${wikiName}.md` });
        (0, import_obsidian.setIcon)(wikiIcon, "file-plus");
        wikiIcon.style.marginLeft = "6px";
        wikiIcon.style.color = "var(--color-purple, #6c5ce7)";
        wikiIcon.onclick = async (e) => {
          e.stopPropagation();
          const folderPath = (0, import_obsidian.normalizePath)(
            this.plugin.settings.conceptNotesFolder || "wiki/02-Concepts"
          );
          if (!(await this.app.vault.adapter.exists(folderPath))) {
            await this.app.vault.createFolder(folderPath);
          }
          const safeTitle = wikiName.replace(/[\/\\:*?"<>|#^\[\]]/g, "-");
          const filePath = `${folderPath}/${safeTitle}.md`;
          const annotation = this.currentFilePath
            ? (this.plugin.settings.comments[this.currentFilePath] || {})[entry.content.trim()] || ""
            : "";
          const sourceLink = this.currentFilePath
            ? `[[${this.currentFilePath.replace(/\.md$/, "").split("/").pop()}]]`
            : "";
          // 已存在 → 追加到末尾
          if (await this.app.vault.adapter.exists(filePath)) {
            const existing = await this.app.vault.adapter.read(filePath);
            const appendLines = [
              "",
              "---",
              `来源: ${sourceLink}`,
              annotation ? `\n${annotation}` : "",
              ""
            ];
            await this.app.vault.adapter.write(filePath, existing.trimEnd() + "\n" + appendLines.join("\n"));
            new import_obsidian.Notice(`📎 已追加到 ${wikiName}.md`);
            return;
          }
          // 构建简洁模板
          const aliasPart = wikiAlias ? `\naliases:\n  - ${wikiAlias}` : "";
          const noteLines = [
            "---",
            `tags:\n  - concept${aliasPart}`,
            "---",
            "",
            `## ${wikiName}`,
            "",
            annotation || "",
            "",
            "---",
            `来源: ${sourceLink}`,
            ""
          ];
          await this.app.vault.adapter.write(filePath, noteLines.join("\n"));
          new import_obsidian.Notice(`✅ Wiki 笔记已创建：${wikiName}.md`);
        };
      }

      const contentEl = card.createDiv({ cls: "extraction-content" });

      if (this.currentFilePath) {
        import_obsidian.MarkdownRenderer.render(this.app, entry.content, contentEl, this.currentFilePath, this);
      } else {
        contentEl.setText(entry.content);
      }
      contentEl.style.marginBottom = "8px";
      contentEl.style.fontSize = "14px";
      contentEl.style.lineHeight = "1.5";
      const comments = this.getComments();
      const contentKey = entry.content.trim();
      const existingComment = comments[contentKey];
      if (existingComment) {
        const commentEl = card.createDiv({ cls: "extraction-comment" });
        if (this.currentFilePath) {
          import_obsidian.MarkdownRenderer.render(this.app, existingComment, commentEl, this.currentFilePath, this);
        } else {
          commentEl.setText(existingComment);
        }
      }
      // Double-click to manually edit comment
      card.addEventListener("dblclick", async (e) => {
        e.preventDefault();
        const currentComment = existingComment || "";
        new CommentModal(this.plugin.app, currentComment, async (newComment) => {
          if (this.currentFilePath) {
            if (!this.plugin.settings.comments[this.currentFilePath]) {
              this.plugin.settings.comments[this.currentFilePath] = {};
            }
            if (newComment) {
              this.plugin.settings.comments[this.currentFilePath][contentKey] = newComment;
              const flashcards = await this.loadFlashcardsData();
              const cardId = `${this.currentFilePath}-${contentKey}`;
              const existingCardIndex = flashcards.findIndex((f) => f.id === cardId);
              const newCard = {
                id: cardId,
                front: entry.content,
                back: newComment,
                source: this.currentFilePath || "",
                timestamp: Date.now(),
                due: Date.now(),
                interval: 1,
                ease: 2.5,
                reviews: 0,
                lapses: 0,
                lastReview: Date.now()
              };
              if (existingCardIndex >= 0) {
                flashcards[existingCardIndex] = newCard;
              } else {
                flashcards.push(newCard);
              }
              await this.saveFlashcardsData(flashcards);
              new import_obsidian.Notice("Saved to Flashcards");
            } else {
              await this.clearAnnotationForEntry(entry);
            }
            await this.plugin.saveSettings();
            setTimeout(() => this.updateView(), 50);
          }
        }).open();
      });
      const footer = card.createDiv({ cls: "extraction-footer" });
      footer.style.display = "flex";
      footer.style.justifyContent = "flex-end";
      const copyIcon = footer.createSpan({ cls: "extraction-copy-icon" });
      copyIcon.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-copy"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>';
      copyIcon.style.cursor = "pointer";
      copyIcon.style.opacity = "0.5";
      copyIcon.style.color = "var(--text-muted)";
      copyIcon.addEventListener("click", async (e) => {
        e.stopPropagation();
        await navigator.clipboard.writeText(entry.content);
        new import_obsidian.Notice("Copied to clipboard");
      });
      footer.appendChild(copyIcon);
    });
  }

  // ── 批量导出概念卡片笔记 ──────────────────────────────────────────
  // 对每条选中条目：
  //   1. 从内容中提取 [[WikiLink]] 作为卡片标题（取第一个）
  //   2. 无 WikiLink 时用内容前 20 字作为标题
  //   3. 附带已保存的注释（annotation）写成结构化 markdown
  //   4. 写入设置中指定的 conceptNotesFolder，文件已存在则跳过
  async exportAsConceptNotes(entries) {
    const folderPath = (0, import_obsidian.normalizePath)(
      this.plugin.settings.conceptNotesFolder || "wiki/02-Concepts"
    );
    // 确保目录存在
    if (!(await this.app.vault.adapter.exists(folderPath))) {
      await this.app.vault.createFolder(folderPath);
    }
    const comments = this.currentFilePath
      ? (this.plugin.settings.comments[this.currentFilePath] || {})
      : {};
    const sourceLink = this.currentFilePath
      ? `[[${this.currentFilePath.replace(/\.md$/, "").split("/").pop()}]]`
      : "";
    let created = 0, skipped = 0;
    for (const entry of entries) {
      const rawContent = entry.content.trim();
      const annotation = comments[rawContent] || "";

      // ── 判断是否为纯单 wiki 链接条目 ──
      const soloMatch = rawContent.match(/^\[\[([^\[\]|]+?)(?:\|([^\]]*))?\.?\]\]$/);

      let cardTitle, safeTitle, lines;

      if (soloMatch) {
        // ── 简洁 Wiki 模板（与单卡片按钮一致）──
        const wikiName  = soloMatch[1].trim();
        const wikiAlias = soloMatch[2]?.trim() || "";
        cardTitle = wikiName;
        safeTitle = wikiName.replace(/[\/\\:*?"<>|#^\[\]]/g, "-");
        const aliasPart = wikiAlias ? `\naliases:\n  - ${wikiAlias}` : "";
        lines = [
          "---",
          `tags:\n  - concept${aliasPart}`,
          "---",
          "",
          `## ${wikiName}`,
          "",
          annotation || "",
          "",
          "---",
          `来源: ${sourceLink}`,
          ""
        ];
      } else {
        // ── 完整摘录模板（含原文 callout）──
        const allWikiLinks = [...rawContent.matchAll(/\[\[([^\[\]|]+?)(?:\|[^\]]*)?\]\]/g)]
          .map(m => m[1].trim())
          .filter((v, i, arr) => arr.indexOf(v) === i);
        cardTitle = allWikiLinks.length > 0
          ? allWikiLinks[0]
          : rawContent.replace(/[\n\r]/g, " ").substring(0, 20).trim();
        safeTitle = cardTitle.replace(/[\/\\:*?"<>|#^\[\]]/g, "-");
        const aliasItems = allWikiLinks.length > 0 ? allWikiLinks : [cardTitle];
        lines = [
          "---",
          "tags:",
          "  - concept",
          "aliases:",
          ...aliasItems.map(a => `  - ${a}`),
          "---",
          "",
          `# [[${cardTitle}]]`,
          "",
          "> [!note] 原文摘录",
          ...rawContent.split("\n").map(l => `> ${l}`),
          ""
        ];
        if (annotation) {
          lines.push("## 注释", "", annotation, "");
        }
        lines.push("---", `来源: ${sourceLink}`, "");
      }

      const filePath = `${folderPath}/${safeTitle}.md`;

      // ── 文件已存在 → 追加到末尾 ──
      if (await this.app.vault.adapter.exists(filePath)) {
        const existing = await this.app.vault.adapter.read(filePath);
        const appendLines = ["", "---", `来源: ${sourceLink}`, annotation ? `\n${annotation}` : "", ""];
        await this.app.vault.adapter.write(filePath, existing.trimEnd() + "\n" + appendLines.join("\n"));
        skipped++;
        continue;
      }

      await this.app.vault.adapter.write(filePath, lines.join("\n"));
      created++;
    }
    return { created, skipped };
  }

  async clearAnnotationForEntry(entry) {
    if (!this.currentFilePath) return false;
    const contentKey = entry.content.trim();
    const fileComments = this.plugin.settings.comments[this.currentFilePath];
    const hasComment = !!(fileComments && fileComments[contentKey]);
    const flashcards = await this.loadFlashcardsData();
    const cardId = `${this.currentFilePath}-${contentKey}`;
    const newFlashcards = flashcards.filter((f) => f.id !== cardId);
    const hasFlashcard = newFlashcards.length !== flashcards.length;
    if (hasComment) {
      delete fileComments[contentKey];
      if (Object.keys(fileComments).length === 0) {
        delete this.plugin.settings.comments[this.currentFilePath];
      }
    }
    if (hasFlashcard) {
      await this.saveFlashcardsData(newFlashcards);
    }
    return hasComment || hasFlashcard;
  }

  async removeOriginalMarkupForEntries(entries) {
    if (!this.currentFilePath || entries.length === 0) return 0;
    const sourceFile = this.app.vault.getAbstractFileByPath(this.currentFilePath);
    if (!(sourceFile instanceof import_obsidian.TFile)) return 0;
    const markdownView = this.findMarkdownViewForCurrentFile();
    let content = await this.app.vault.read(sourceFile);
    let removed = 0;
    const removableEntries = entries.filter((entry) => entry.fullMatch && entry.fullMatch !== entry.content);
    for (const entry of removableEntries) {
      const nextContent = this.replaceEntryMarkup(content, entry);
      if (nextContent === content) continue;
      content = nextContent;
      removed++;
    }
    if (removed === 0) return 0;
    await this.app.vault.modify(sourceFile, content);
    if (markdownView) {
      markdownView.editor.setValue(content);
    }
    return removed;
  }

  findMarkdownViewForCurrentFile() {
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian.MarkdownView && view.file && view.file.path === this.currentFilePath) {
        return view;
      }
    }
    return null;
  }

  replaceEntryMarkup(content, entry) {
    const fullMatch = entry.fullMatch;
    const replacement = entry.content;
    const exactIndex = content.indexOf(fullMatch);
    if (exactIndex === -1) return content;
    return content.slice(0, exactIndex) + replacement + content.slice(exactIndex + fullMatch.length);
  }

  async loadFlashcardsData() {
    const path = this.getFlashcardsJsonPath();
    if (await this.app.vault.adapter.exists(path)) {
      const content = await this.app.vault.adapter.read(path);
      try {
        return JSON.parse(content);
      } catch (e) {
        console.error("Failed to parse flashcards.json", e);
        return [];
      }
    }
    return [];
  }
  async saveFlashcardsData(cards) {
    const path = this.getFlashcardsJsonPath();
    await this.ensureParentFolderExists(path);
    await this.app.vault.adapter.write(path, JSON.stringify(cards, null, 2));
    if (this.plugin.settings.saveFlashcardsToMarkdown) {
      await this.saveFlashcardsMarkdown(cards);
    }
  }
  getFlashcardsJsonPath() {
    return this.plugin.settings.flashcardsPath || ".flashcards/hinote.json";
  }
  getFlashcardsMarkdownPath() {
    return ".flashcards/flashcards.md";
  }
  async ensureParentFolderExists(path) {
    const lastSlash = path.lastIndexOf("/");
    if (lastSlash === -1) return;
    const folderPath = path.slice(0, lastSlash);
    if (!folderPath) return;
    if (!(await this.app.vault.adapter.exists(folderPath))) {
      await this.app.vault.createFolder(folderPath);
    }
  }
  async saveFlashcardsMarkdown(cards) {
    const markdownPath = this.getFlashcardsMarkdownPath();
    await this.ensureParentFolderExists(markdownPath);
    const lines = cards.map((card) => {
      const front = (card.front || "").replace(/\r?\n+/g, " ").trim();
      const back = (card.back || "").replace(/\r?\n+/g, " ").trim();
      const sourceName = card.source ? card.source.replace(/\.md$/, "").split("/").pop() : "";
      const sourceText = sourceName ? `[[${sourceName}]]` : "";
      return `- ${front}: ${back}${sourceText ? ` (${sourceText})` : ""}`;
    });
    await this.app.vault.adapter.write(markdownPath, lines.join("\n"));
  }
};

// ── CommentModal ─────────────────────────────────────────────────
var CommentModal = class extends import_obsidian.Modal {
  constructor(app, defaultComment, onSubmit) {
    super(app);
    this.comment = defaultComment;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Add/Edit Comment" });
    const setting = new import_obsidian.Setting(contentEl).addTextArea(
      (text) => text.setValue(this.comment).onChange((value) => {
        this.comment = value;
      })
    );
    const textArea = setting.controlEl.querySelector("textarea");
    if (textArea) {
      textArea.style.width = "100%";
      textArea.style.height = "100px";
      textArea.placeholder = "Add your thought here... (Cmd+Enter to save)";
      textArea.addEventListener("keydown", (e) => {
        if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
          e.preventDefault();
          this.close();
          this.onSubmit(this.comment);
        }
      });
      setTimeout(() => textArea.focus(), 50);
    }
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("Save").setCta().onClick(() => {
      this.close();
      this.onSubmit(this.comment);
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// ── CalloutExportPlugin ──────────────────────────────────────────
var CalloutExportPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading Callout Export Plugin");
    await this.loadSettings();
    if (!this.settings.aiProfiles || this.settings.aiProfiles.length === 0) {
      const legacyKey = this.settings.openAIApiKey || "";
      const legacyUrl = this.settings.customServerUrl || "https://api.openai.com/v1/chat/completions";
      const legacyModel = this.settings.aiModel || "gpt-3.5-turbo";
      this.settings.aiProfiles = [
        {
          id: "default-highlights",
          name: "Highlights Annotation",
          url: legacyUrl,
          apiKey: legacyKey,
          model: legacyModel,
          prompt: "\u7528\u7B80\u6D01\u7684\u4E2D\u6587\u5BF9\u4EE5\u4E0B\u5212\u7EBF\u5185\u5BB9\u7ED9\u51FA\u6CE8\u91CA\u6216\u89E3\u91CA\uFF0C100\u5B57\u4EE5\u5185\u3002"
        },
        {
          id: "default-custom",
          name: "Custom",
          url: legacyUrl,
          apiKey: legacyKey,
          model: legacyModel,
          prompt: this.settings.customAiPrompt || ""
        }
      ];
      await this.saveSettings();
    }
    this.addCommand({
      id: "open-my-hinote",
      name: "Open My HiNote",
      callback: () => {
        this.activateView();
      }
    });

    this.registerView(
      VIEW_TYPE_EXTRACTION,
      (leaf) => new ExtractionView(leaf, this)
    );
    this.addRibbonIcon("star", "Open Highlights View", () => {
      this.activateView();
    });

    // Ensure view is automatically opened on load/activation if layout is ready
    this.app.workspace.onLayoutReady(() => {
      this.activateView();
    });

    const updateDebounced = (0, import_obsidian.debounce)(() => {
      this.updateExtractionView();
    }, 500, true);
    this.registerEvent(this.app.workspace.on("file-open", () => this.updateExtractionView()));
    this.registerEvent(this.app.workspace.on("editor-change", updateDebounced));
    this.addSettingTab(new CalloutExportSettingTab(this.app, this));
    console.log("My HiNote Plugin loaded successfully");
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_EXTRACTION);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) await leaf.setViewState({ type: VIEW_TYPE_EXTRACTION, active: true });
    }
    if (leaf) workspace.revealLeaf(leaf);
  }
  updateExtractionView() {
    const file = this.app.workspace.getActiveFile();
    const activePath = file ? file.path : null;
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_EXTRACTION);
    for (const leaf of leaves) {
      if (leaf.view instanceof ExtractionView) {
        leaf.view.currentFilePath = activePath;
        leaf.view.updateView();
      }
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Parse callout blocks and extract entries with date links
   *
   * Supported format:
   * > [!note]
   * > - text content
   * > ^block-id (skipped)
   * >    - [[YYYYMMDD|YYYYMMDDHHmm]]
   *
   * Supports both tab and space indentation
   * Also supports default calls > [!note] without date links (uses today's date)
   */
  extractCallouts(content) {
    const entries = [];
    const indent = "(?:\\t|    )";
    const blockRefPattern = /^\^/;
    const getToday = () => {
      const now = /* @__PURE__ */ new Date();
      const y = now.getFullYear();
      const m = (now.getMonth() + 1).toString().padStart(2, "0");
      const d = now.getDate().toString().padStart(2, "0");
      return `${y}${m}${d}`;
    };
    let currentTime = /* @__PURE__ */ new Date();
    let timeCounter = 0;
    const calloutHeaderPattern = /^> \[!note\]/gm;
    let headerMatch;
    while ((headerMatch = calloutHeaderPattern.exec(content)) !== null) {
      const startIndex = headerMatch.index;
      const contentFromStart = content.substring(startIndex);
      const lines = contentFromStart.split("\n");
      const entryLines = [];
      let dateLink = null;
      entryLines.push(lines[0]);
      for (let i = 1; i < lines.length; i++) {
        const line = lines[i];
        if (!line.startsWith(">")) break;
        if (/^> \[!/.test(line)) break;
        const dateLinkMatchWithTime = line.match(new RegExp(`^> ${indent}- \\[\\[.*?\\|(\\d{8})(\\d{2})(\\d{2})\\]\\]`));
        const dateLinkMatchNoTime = line.match(new RegExp(`^> ${indent}- \\[\\[(\\d{8})\\]\\]`));
        if (dateLinkMatchWithTime) {
          dateLink = {
            date: dateLinkMatchWithTime[1],
            time: `${dateLinkMatchWithTime[2]}:${dateLinkMatchWithTime[3]}`
          };
        } else if (dateLinkMatchNoTime) {
          dateLink = {
            date: dateLinkMatchNoTime[1],
            time: null
          };
        }
        entryLines.push(line);
      }
      const textParts = [];
      for (const line of entryLines) {
        if (/^> \[!/.test(line)) continue;
        let contentLine = line;
        if (contentLine.startsWith(">")) {
          contentLine = contentLine.substring(1);
          if (contentLine.startsWith(" ")) {
            contentLine = contentLine.substring(1);
          }
        }
        if (blockRefPattern.test(contentLine.trim())) continue;
        if (contentLine.trim().startsWith("- [[") && contentLine.includes("]]")) continue;
        textParts.push(contentLine);
      }
      if (textParts.length === 0) continue;
      while (textParts.length > 0 && textParts[0].trim() === "") textParts.shift();
      while (textParts.length > 0 && textParts[textParts.length - 1].trim() === "") textParts.pop();
      const combinedText = textParts.join("\n");
      let date = dateLink ? dateLink.date : getToday();
      let time;
      if (dateLink && dateLink.time !== null) {
        time = dateLink.time;
      } else {
        const autoTime = new Date(currentTime.getTime() + timeCounter * 6e4);
        const h = autoTime.getHours().toString().padStart(2, "0");
        const m = autoTime.getMinutes().toString().padStart(2, "0");
        timeCounter++;
        time = `${h}:${m}`;
      }
      entries.push({
        text: combinedText,
        date,
        time
      });
    }
    return entries;
  }
  /**
   * Group entries by date
   */
  groupByDate(entries) {
    const grouped = /* @__PURE__ */ new Map();
    for (const entry of entries) {
      if (!grouped.has(entry.date)) {
        grouped.set(entry.date, []);
      }
      grouped.get(entry.date).push(entry);
    }
    return grouped;
  }
  /**
   * Insert content between two sections in a file
   */
  insertBetweenSections(content, startSection, endSection, newContent) {
    const startIndex = content.indexOf(startSection);
    const endIndex = content.indexOf(endSection);
    if (startIndex === -1 || endIndex === -1) {
      return content + "\n\n" + startSection + "\n\n" + newContent + "\n\n" + endSection + "\n";
    }
    if (startIndex >= endIndex) {
      new import_obsidian.Notice("Warning: Section order is incorrect. Appending to end.");
      return content + "\n" + newContent;
    }
    const startLineEnd = content.indexOf("\n", startIndex);
    if (startLineEnd === -1) {
      return content + "\n" + newContent;
    }
    const beforeStart = content.substring(0, startLineEnd + 1);
    const existingBetween = content.substring(startLineEnd + 1, endIndex);
    const afterEnd = content.substring(endIndex);
    const extractNoteText = (line) => {
      const match = line.match(/#\w+ (.+?) \(\[\[/);
      return match ? match[1] : line;
    };
    const existingNoteTexts = existingBetween.split("\n").filter((line) => line.trim()).map((line) => extractNoteText(line));
    const newLines = newContent.split("\n").filter((line) => line.trim());
    const filteredNewLines = newLines.filter((line) => {
      const noteText = extractNoteText(line);
      return !existingNoteTexts.includes(noteText);
    });
    if (filteredNewLines.length === 0) {
      return content;
    }
    const insertContent = filteredNewLines.join("\n") + "\n";
    return beforeStart + insertContent + existingBetween + afterEnd;
  }
  async exportToDailyNotes(editor, view) {
    const content = editor.getValue();
    const entries = this.extractCallouts(content);
    if (entries.length === 0) {
      new import_obsidian.Notice("No callout entries with date links found.");
      return;
    }
    await this.performExport(editor, view, entries, "note");
  }
  async performExport(editor, view, entries, tag) {
    const currentFile = view.file;
    const noteTitle = currentFile ? currentFile.basename : "Unknown";
    const groupedEntries = this.groupByDate(entries);
    let exportedCount = 0;
    const folderPath = this.settings.dailyNotesFolder ? (0, import_obsidian.normalizePath)(this.settings.dailyNotesFolder) : "";
    if (folderPath) {
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (!folder) {
        await this.app.vault.createFolder(folderPath);
      }
    }
    for (const [date, entryList] of groupedEntries) {
      const pathPrefix = folderPath ? folderPath + "/" : "";
      const fileName = `${pathPrefix}${date}.md`;
      const formattedContent = entryList.map((e) => {
        const timeStr = e.time || "00:00";
        let template = this.settings.calloutExportTemplate || "- {{time}} #note {{content}} ([[SourceNote]])";
        template = template.replace(/{{time}}/g, timeStr).replace(/{{sourceTitle}}/g, noteTitle).replace(/{{sourceLink}}/g, `[[${noteTitle}]]`).replace(/\[\[SourceNote\]\]/g, `[[${noteTitle}]]`);
        const lines = e.text.split("\n");
        let finalEntry = "";
        if (lines.length === 1) {
          const content = lines[0].replace(/^- /, "");
          finalEntry = template.replace(/{{content}}/g, content);
        } else {
          const firstLineContent = lines[0].replace(/^- /, "");
          const firstLine = template.replace(/{{content}}/g, firstLineContent);
          const restLines = lines.slice(1).join("\n");
          finalEntry = `${firstLine}\n${restLines}`;
        }
        if (currentFile) {
          const comments = this.settings.comments[currentFile.path] || {};
          const comment = comments[e.text.trim()];
          if (comment) {
            finalEntry += `\n\t- ${comment}`;
          }
        }
        return finalEntry;
      }).join("\n");
      console.log(`[Callout Export] Processing ${date} with ${entryList.length} entries`);
      let file = this.app.vault.getAbstractFileByPath(fileName);
      if (file instanceof import_obsidian.TFile) {
        const fileContent = await this.app.vault.read(file);
        const newContent = this.insertBetweenSections(
          fileContent,
          this.settings.readingSection,
          this.settings.logSection,
          formattedContent
        );
        if (newContent !== fileContent) {
          await this.app.vault.modify(file, newContent);
          exportedCount++;
        }
      } else {
        let template = this.settings.dailyNoteTemplate;
        if (!template.includes("{{content}}")) {
          template = template.replace(
            /{{readingSection}}/g,
            "{{readingSection}}\n\n{{content}}"
          );
        }
        let newFileContent = template.replace(/{{date}}/g, date).replace(/{{readingSection}}/g, this.settings.readingSection).replace(/{{logSection}}/g, this.settings.logSection).replace(/{{content}}/g, formattedContent);
        await this.app.vault.create(fileName, newFileContent);
        exportedCount++;
      }
    }
    new import_obsidian.Notice(`Exported ${entries.length} callout entries to ${exportedCount} daily note(s).`);
  }
  extractMatches(content) {
    const entries = [];
    for (const rule of this.settings.customRegexes) {
      try {
        const regex = new RegExp(rule.regex, "gm");
        const matches = [...content.matchAll(regex)];
        for (const match of matches) {
          const innerContent = match.length > 1 ? match[1] : match[0];
          entries.push({
            ruleName: rule.name,
            template: rule.template,
            content: innerContent,
            fullMatch: match[0],
            index: match.index
          });
        }
      } catch (e) {
        console.error(`[Export] Error parsing regex for rule '${rule.name}':`, e);
      }
    }
    entries.sort((a, b) => a.index - b.index);
    return entries;
  }
  /**
   * Export all color text entries AND highlights to daily note
   * Parses all <font color="...">text</font> and ==text== in the current note
   * Uses current time for all entries
   */
  async exportColorTextToDailyNote(editor, view) {
    const content = editor.getValue();
    console.log("[Color/Highlight Export] Parsing note content...");
    const entries = this.extractMatches(content);
    if (entries.length === 0) {
      new import_obsidian.Notice("No matching entries found in note");
      return;
    }
    console.log(`[Color/Highlight Export] Found ${entries.length} entries`);
    const now = /* @__PURE__ */ new Date();
    const hours = now.getHours().toString().padStart(2, "0");
    const minutes = now.getMinutes().toString().padStart(2, "0");
    const timeStr = `${hours}:${minutes}`;
    const year = now.getFullYear();
    const month = (now.getMonth() + 1).toString().padStart(2, "0");
    const day = now.getDate().toString().padStart(2, "0");
    const dateStr = `${year}${month}${day}`;
    const currentFile = view.file;
    const noteTitle = currentFile ? currentFile.basename : "Unknown";
    const formattedEntries = [];
    for (const entry of entries) {
      let template = entry.template;
      template = template.replace(/{{time}}/g, timeStr).replace(/{{sourceTitle}}/g, noteTitle).replace(/{{sourceLink}}/g, `[[${noteTitle}]]`).replace(/\[\[SourceNote\]\]/g, `[[${noteTitle}]]`);
      let formattedEntry = template.replace(/{{content}}/g, entry.content);
      if (currentFile) {
        const comments = this.settings.comments[currentFile.path] || {};
        const comment = comments[entry.content.trim()];
        if (comment) {
          formattedEntry += `\n\t- ${comment}`;
        }
      }
      formattedEntries.push(formattedEntry);
      console.log(`[Export] Rule '${entry.ruleName}': ${entry.content.substring(0, 50)}...`);
    }
    const formattedContent = formattedEntries.join("\n");
    const folderPath = this.settings.dailyNotesFolder ? (0, import_obsidian.normalizePath)(this.settings.dailyNotesFolder) : "";
    if (folderPath) {
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (!folder) {
        await this.app.vault.createFolder(folderPath);
      }
    }
    const pathPrefix = folderPath ? folderPath + "/" : "";
    const fileName = `${pathPrefix}${dateStr}.md`;
    console.log("[Export] File name:", fileName);
    console.log("[Export] Formatted content:", formattedContent);
    let file = this.app.vault.getAbstractFileByPath(fileName);
    if (file instanceof import_obsidian.TFile) {
      console.log("[Export] File exists, updating...");
      const fileContent = await this.app.vault.read(file);
      const newContent = this.insertBetweenSections(
        fileContent,
        this.settings.readingSection,
        this.settings.logSection,
        formattedContent
      );
      if (newContent !== fileContent) {
        await this.app.vault.modify(file, newContent);
        new import_obsidian.Notice(`Exported to ${dateStr}.md`);
        console.log("[Export] File updated successfully");
      } else {
        new import_obsidian.Notice("Content already exists in daily note");
        console.log("[Export] Content already exists");
      }
    } else {
      console.log("[Export] Creating new file...");
      let template = this.settings.dailyNoteTemplate;
      if (!template.includes("{{content}}")) {
        template = template.replace(
          /{{readingSection}}/g,
          "{{readingSection}}\n\n{{content}}"
        );
      }
      let newFileContent = template.replace(/{{date}}/g, dateStr).replace(/{{readingSection}}/g, this.settings.readingSection).replace(/{{logSection}}/g, this.settings.logSection).replace(/{{content}}/g, formattedContent);
      await this.app.vault.create(fileName, newFileContent);
      new import_obsidian.Notice(`Created ${dateStr}.md with entry`);
    }
  }
  async exportSingleEntry(entry, sourceFile) {
    const now = /* @__PURE__ */ new Date();
    const hours = now.getHours().toString().padStart(2, "0");
    const minutes = now.getMinutes().toString().padStart(2, "0");
    const timeStr = `${hours}:${minutes}`;
    const year = now.getFullYear();
    const month = (now.getMonth() + 1).toString().padStart(2, "0");
    const day = now.getDate().toString().padStart(2, "0");
    const dateStr = `${year}${month}${day}`;
    const noteTitle = sourceFile.basename;
    let template = entry.template;
    if (!template) template = this.settings.calloutExportTemplate;
    let formattedEntry = template.replace(/{{time}}/g, timeStr).replace(/{{sourceTitle}}/g, noteTitle).replace(/{{sourceLink}}/g, `[[${noteTitle}]]`).replace(/\[\[SourceNote\]\]/g, `[[${noteTitle}]]`).replace(/{{content}}/g, entry.content);
    const comments = this.settings.comments[sourceFile.path] || {};
    const comment = comments[entry.content.trim()];
    if (comment) {
      formattedEntry += `\n\t- ${comment}`;
    }
    const folderPath = this.settings.dailyNotesFolder ? (0, import_obsidian.normalizePath)(this.settings.dailyNotesFolder) : "";
    const fileName = (folderPath ? folderPath + "/" : "") + `${dateStr}.md`;
    let file = this.app.vault.getAbstractFileByPath(fileName);
    if (!file && folderPath) {
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (!folder) await this.app.vault.createFolder(folderPath);
    }
    if (file instanceof import_obsidian.TFile) {
      const fileContent = await this.app.vault.read(file);
      const newContent = this.insertBetweenSections(
        fileContent,
        this.settings.readingSection,
        this.settings.logSection,
        formattedEntry
      );
      if (newContent !== fileContent) {
        await this.app.vault.modify(file, newContent);
        new import_obsidian.Notice("Exported to Daily Note");
      }
    } else {
      let template2 = this.settings.dailyNoteTemplate;
      if (!template2.includes("{{content}}")) {
        template2 = template2.replace(/{{readingSection}}/g, "{{readingSection}}\n\n{{content}}");
      }
      const newContent = template2.replace(/{{date}}/g, dateStr).replace(/{{readingSection}}/g, this.settings.readingSection).replace(/{{logSection}}/g, this.settings.logSection).replace(/{{content}}/g, formattedEntry);
      await this.app.vault.create(fileName, newContent);
      new import_obsidian.Notice("Created Daily Note with export");
    }
  }
  onunload() {
    console.log("Unloading Callout Export Plugin");
  }
};

// ── Settings Tab ─────────────────────────────────────────────────
var CalloutExportSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Callout Export Settings" });
    new import_obsidian.Setting(containerEl).setName("Daily Notes Folder").setDesc("Folder where daily notes are stored. Leave empty for vault root.").addText((text) => text.setPlaceholder("").setValue(this.plugin.settings.dailyNotesFolder).onChange(async (value) => {
      this.plugin.settings.dailyNotesFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Reading Section").setDesc("Section header to insert after (e.g., ## \u9605\u8BFB)").addText((text) => text.setPlaceholder("## \u9605\u8BFB").setValue(this.plugin.settings.readingSection).onChange(async (value) => {
      this.plugin.settings.readingSection = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Log Section").setDesc("Section header to insert before (e.g., ## \u65E5\u5FD7)").addText((text) => text.setPlaceholder("## \u65E5\u5FD7").setValue(this.plugin.settings.logSection).onChange(async (value) => {
      this.plugin.settings.logSection = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Daily Note Template").setDesc("Template for creating new daily notes. Placeholders: {{date}}, {{readingSection}}, {{logSection}}, {{content}}").addTextArea((text) => {
      text.setPlaceholder("# {{date}}\n\n{{readingSection}}\n\n{{content}}\n\n{{logSection}}").setValue(this.plugin.settings.dailyNoteTemplate).onChange(async (value) => {
        this.plugin.settings.dailyNoteTemplate = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 8;
      text.inputEl.cols = 40;
    });

    // ── AI Profiles (used for inline annotation) ──
    const aiDetails = containerEl.createEl("details");
    aiDetails.open = false;
    const summary = aiDetails.createEl("summary", { text: "AI Profiles (Highlight Annotation)" });
    summary.style.fontSize = "1.2em";
    summary.style.fontWeight = "bold";
    summary.style.marginBottom = "10px";
    summary.style.cursor = "pointer";
    aiDetails.createEl("p", { text: "Configure AI profiles used for one-click Chinese annotation on each highlight card. The first profile (or last active) will be used." });

    // Active profile selector
    if (this.plugin.settings.aiProfiles.length > 0) {
      new import_obsidian.Setting(aiDetails).setName("Active Profile").setDesc("Profile used for AI annotation button on each card.").addDropdown((drop) => {
        this.plugin.settings.aiProfiles.forEach((p) => drop.addOption(p.id, p.name));
        drop.setValue(this.plugin.settings.lastActiveProfileId || this.plugin.settings.aiProfiles[0].id);
        drop.onChange(async (val) => {
          this.plugin.settings.lastActiveProfileId = val;
          await this.plugin.saveSettings();
        });
      });
    }

    new import_obsidian.Setting(aiDetails).setName("Add New Profile").setDesc("Create a new AI configuration.").addButton((button) => button.setButtonText("Add Profile").setCta().onClick(async () => {
      const newProfile = {
        id: Date.now().toString(),
        name: "New Profile",
        url: "https://api.openai.com/v1/chat/completions",
        apiKey: "",
        model: "gpt-3.5-turbo",
        prompt: "\u7528\u7B80\u6D01\u7684\u4E2D\u6587\u5BF9\u4EE5\u4E0B\u5212\u7EBF\u5185\u5BB9\u7ED9\u51FA\u6CE8\u91CA\u6216\u89E3\u91CA\uFF0C100\u5B57\u4EE5\u5185\u3002"
      };
      this.plugin.settings.aiProfiles.push(newProfile);
      await this.plugin.saveSettings();
      this.display();
    }));
    this.plugin.settings.aiProfiles.forEach((profile, index) => {
      const div = aiDetails.createDiv({ cls: "ai-profile-container" });
      div.style.border = "1px solid var(--background-modifier-border)";
      div.style.padding = "10px";
      div.style.marginBottom = "10px";
      div.style.borderRadius = "5px";
      div.style.display = "flex";
      div.style.justifyContent = "space-between";
      div.style.alignItems = "center";
      const infoDiv = div.createDiv();
      infoDiv.createEl("b", { text: profile.name });
      const modelSpan = infoDiv.createEl("span", { text: ` (${profile.model})` });
      modelSpan.style.color = "var(--text-muted)";
      modelSpan.style.fontSize = "0.9em";
      const btnDiv = div.createDiv();
      btnDiv.style.display = "flex";
      btnDiv.style.gap = "8px";
      new import_obsidian.Setting(btnDiv).addButton((btn) => btn.setButtonText("Edit").onClick(() => {
        new ProfileEditModal(this.app, profile, async (updated) => {
          this.plugin.settings.aiProfiles[index] = updated;
          await this.plugin.saveSettings();
          this.display();
        }).open();
      }));
      new import_obsidian.Setting(btnDiv).addButton((btn) => btn.setButtonText("Delete").setWarning().onClick(async () => {
        if (confirm(`Delete profile "${profile.name}"?`)) {
          this.plugin.settings.aiProfiles.splice(index, 1);
          await this.plugin.saveSettings();
          this.display();
        }
      }));
    });

    new import_obsidian.Setting(containerEl).setName("概念卡片笔记目录").setDesc("批量导出含 [[链接]] 的高亮时，生成的概念笔记存放路径。默认：wiki/02-Concepts").addText((text) => text.setPlaceholder("wiki/02-Concepts").setValue(this.plugin.settings.conceptNotesFolder || "wiki/02-Concepts").onChange(async (value) => {
      this.plugin.settings.conceptNotesFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Flashcards Path").setDesc("Path to the flashcards JSON file.").addText((text) => text.setPlaceholder(".flashcards/hinote.json").setValue(this.plugin.settings.flashcardsPath).onChange(async (value) => {
      this.plugin.settings.flashcardsPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Save Flashcards as Markdown").setDesc("If enabled, flashcards will also be exported to .flashcards/flashcards.md as one line per card.").addToggle((toggle) => toggle.setValue(this.plugin.settings.saveFlashcardsToMarkdown).onChange(async (value) => {
      this.plugin.settings.saveFlashcardsToMarkdown = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Callout Export Template").setDesc("Format for exported callouts. Placeholders: {{time}}, {{content}}, {{sourceTitle}}, {{sourceLink}} (equals [[{{sourceTitle}}]]), [[SourceNote]]").addText((text) => text.setPlaceholder("- {{time}} #note {{content}} ([[SourceNote]])").setValue(this.plugin.settings.calloutExportTemplate).onChange(async (value) => {
      this.plugin.settings.calloutExportTemplate = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Custom Note Extraction Rules").setHeading();
    new import_obsidian.Setting(containerEl).setName("Add New Rule").setDesc("Add a new custom regex rule for extraction.").addButton((button) => button.setButtonText("Add Rule").onClick(async () => {
      this.plugin.settings.customRegexes.push({
        name: "New Rule",
        regex: "",
        template: "- {{time}} #custom {{content}} ([[SourceNote]])"
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    this.plugin.settings.customRegexes.forEach((rule, index) => {
      const div = containerEl.createDiv({ cls: "custom-rule-container" });
      div.style.border = "1px solid #ccc";
      div.style.padding = "10px";
      div.style.marginBottom = "10px";
      div.style.borderRadius = "5px";
      new import_obsidian.Setting(div).setName("Rule Name").addText((text) => text.setValue(rule.name).onChange(async (value) => {
        rule.name = value;
        await this.plugin.saveSettings();
      })).addButton((button) => button.setButtonText("Remove").setWarning().onClick(async () => {
        this.plugin.settings.customRegexes.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      }));
      new import_obsidian.Setting(div).setName("Regex Pattern").setDesc("Input Regex pattern. Use capture group (content) to extract text.").addText((text) => text.setPlaceholder("e.g. ==(.*?)==").setValue(rule.regex).onChange(async (value) => {
        rule.regex = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(div).setName("Export Template").setDesc("Template with {{time}}, {{content}}, {{sourceTitle}}").addText((text) => text.setPlaceholder("- {{time}} #tag {{content}}").setValue(rule.template).onChange(async (value) => {
        rule.template = value;
        await this.plugin.saveSettings();
      }));
    });
  }
};

// ── ProfileEditModal ──────────────────────────────────────────────
var ProfileEditModal = class extends import_obsidian.Modal {
  constructor(app, profile, onSubmit) {
    super(app);
    this.profile = { ...profile };
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Edit AI Profile" });
    new import_obsidian.Setting(contentEl).setName("Profile Name").addText((text) => text.setValue(this.profile.name).onChange((val) => this.profile.name = val));
    new import_obsidian.Setting(contentEl).setName("API URL").setDesc("Base URL (e.g., https://api.openai.com/v1/chat/completions)").addText((text) => text.setValue(this.profile.url).onChange((val) => this.profile.url = val));
    new import_obsidian.Setting(contentEl).setName("API Key").addText((text) => text.setPlaceholder("sk-...").setValue(this.profile.apiKey).onChange((val) => this.profile.apiKey = val));
    new import_obsidian.Setting(contentEl).setName("Model Name").addText((text) => text.setValue(this.profile.model).onChange((val) => this.profile.model = val));
    new import_obsidian.Setting(contentEl).setName("Prompt Template").setDesc("Use {{source-note}}, {{current-high-notes}}, {{flashcards}}").addTextArea((text) => {
      text.setValue(this.profile.prompt).onChange((val) => this.profile.prompt = val);
      text.inputEl.rows = 5;
      text.inputEl.style.width = "100%";
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("Save").setCta().onClick(() => {
      this.onSubmit(this.profile);
      this.close();
    }));
  }
  onClose() {
    this.contentEl.empty();
  }
};