/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/


var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DocumentAnalyzerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/services/ai-service.ts
var import_obsidian = require("obsidian");
var AIService = class {
  constructor(config) {
    this.config = config;
  }
  /**
   * Analyze document content using AI
   */
  async analyzeDocument(content, fieldConfig) {
    if (!this.config.apiKey) {
      throw new Error("API\u5BC6\u94A5\u672A\u914D\u7F6E");
    }
    const prompt = this.buildPrompt(content, fieldConfig);
    try {
      if (this.config.provider === "openai" || this.config.provider === "custom") {
        return await this.queryOpenAI(prompt);
      } else if (this.config.provider === "anthropic") {
        return await this.queryAnthropic(prompt);
      }
      throw new Error("\u4E0D\u652F\u6301\u7684AI\u63D0\u4F9B\u5546");
    } catch (error) {
      if (error.status === 401) {
        throw new Error("API\u5BC6\u94A5\u65E0\u6548\uFF0C\u8BF7\u68C0\u67E5\u8BBE\u7F6E");
      } else if (error.status === 429) {
        throw new Error("API\u914D\u989D\u5DF2\u7528\u5B8C\uFF0C\u8BF7\u7A0D\u540E\u518D\u8BD5");
      } else if (error.status === 500) {
        throw new Error("AI\u670D\u52A1\u6682\u65F6\u4E0D\u53EF\u7528");
      }
      throw error;
    }
  }
  /**
   * Query OpenAI API
   */
  async queryOpenAI(prompt) {
    var _a, _b, _c;
    const response = await (0, import_obsidian.requestUrl)({
      url: `${this.config.baseURL}/chat/completions`,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.config.apiKey}`
      },
      body: JSON.stringify({
        model: this.config.model || "gpt-3.5-turbo",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.7,
        max_tokens: this.config.maxTokens || 1e3
      })
    });
    const data = response.json;
    if (data.error) {
      throw new Error(data.error.message || "API\u9519\u8BEF");
    }
    const result = (_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
    if (!result) {
      throw new Error("AI\u8FD4\u56DE\u7A7A\u5185\u5BB9");
    }
    return result;
  }
  /**
   * Query Anthropic Claude API
   */
  async queryAnthropic(prompt) {
    var _a, _b;
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://api.anthropic.com/v1/messages",
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.config.apiKey,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model: this.config.model || "claude-3-sonnet-20240229",
        max_tokens: this.config.maxTokens || 1e3,
        messages: [{ role: "user", content: prompt }]
      })
    });
    const data = response.json;
    if (data.error) {
      throw new Error(data.error.message || "API\u9519\u8BEF");
    }
    const result = (_b = (_a = data.content) == null ? void 0 : _a[0]) == null ? void 0 : _b.text;
    if (!result) {
      throw new Error("AI\u8FD4\u56DE\u7A7A\u5185\u5BB9");
    }
    return result;
  }
  /**
   * Build prompt for document analysis based on enabled fields
   */
  /**
   * Build prompt for document analysis based on enabled fields
   */
  buildPrompt(content, fieldConfig) {
    let requirements = "";
    let exampleJsonObj = {};
    const fields = fieldConfig.fields || [];
    fields.forEach((field, index) => {
      if (!field.enabled)
        return;
      let reqDesc = `${index + 1}. ${field.key}: ${field.description}`;
      if (field.type === "select" && field.options) {
        reqDesc += ` (\u53EF\u9009\u503C: ${field.options.join(", ")})`;
      }
      requirements += reqDesc + "\n";
      if (field.type === "array") {
        exampleJsonObj[field.key] = ["item1", "item2"];
      } else if (field.type === "select") {
        exampleJsonObj[field.key] = field.options && field.options.length > 0 ? field.options[0] : "value";
      } else {
        exampleJsonObj[field.key] = "value";
      }
    });
    return `\u5206\u6790\u4EE5\u4E0B\u6587\u6863\u5185\u5BB9\uFF0C\u63D0\u53D6\u7ED3\u6784\u5316\u5143\u6570\u636E\u3002

\u8981\u6C42\uFF1A
${requirements}
\u8BF7\u53EA\u8FD4\u56DE\u7EAFJSON\u683C\u5F0F\uFF0C\u4E0D\u8981\u5305\u542B\u4EFB\u4F55\u5176\u4ED6\u6587\u5B57\u8BF4\u660E\u3002\u683C\u5F0F\u5982\u4E0B\uFF1A
${JSON.stringify(exampleJsonObj, null, 2)}

\u6587\u6863\u5185\u5BB9\uFF1A
${content.substring(0, 3e3)}`;
  }
};

// src/services/document-analyzer.ts
var DocumentAnalyzer = class {
  constructor(aiService, settings) {
    this.aiService = aiService;
    this.settings = settings;
  }
  /**
   * Analyze document and return metadata
   */
  async analyze(content) {
    if (!content || content.trim().length < 50) {
      return {
        success: false,
        error: "\u6587\u6863\u5185\u5BB9\u592A\u77ED\uFF0C\u65E0\u6CD5\u5206\u6790\uFF08\u81F3\u5C11\u9700\u898150\u4E2A\u5B57\u7B26\uFF09"
      };
    }
    if (!this.hasEnabledFields()) {
      return {
        success: false,
        error: "\u8BF7\u81F3\u5C11\u542F\u7528\u4E00\u4E2AYAML\u5B57\u6BB5"
      };
    }
    try {
      const response = await this.aiService.analyzeDocument(content, this.settings);
      const metadata = this.parseResponse(response);
      const filteredMetadata = this.filterDisabledFields(metadata);
      return {
        success: true,
        metadata: filteredMetadata
      };
    } catch (error) {
      return {
        success: false,
        error: error.message || "\u6587\u6863\u5206\u6790\u5931\u8D25"
      };
    }
  }
  /**
   * Check if at least one field is enabled
   */
  hasEnabledFields() {
    return this.settings.fields.some((f) => f.enabled);
  }
  /**
   * Filter out disabled fields from metadata
   */
  filterDisabledFields(metadata) {
    const filtered = {};
    this.settings.fields.forEach((field) => {
      if (field.enabled && metadata[field.key] !== void 0) {
        filtered[field.key] = metadata[field.key];
      }
    });
    return filtered;
  }
  /**
   * Parse AI response and extract metadata
   */
  parseResponse(content) {
    try {
      const parsed = JSON.parse(content.trim());
      return parsed;
    } catch (error) {
      console.error("Failed to parse AI response:", error);
      const jsonMatch = content.match(/```(?:json)?\s*\n?([\s\S]*?)\n?```/);
      if (jsonMatch) {
        try {
          const parsed = JSON.parse(jsonMatch[1].trim());
          return parsed;
        } catch (e) {
          console.error("Failed to parse extracted JSON:", e);
        }
      }
      return {};
    }
  }
};

// src/utils/yaml-helper.ts
var import_obsidian2 = require("obsidian");
var YamlHelper = class {
  /**
   * Parse document content to extract YAML frontmatter and body
   */
  static parseFrontmatter(content) {
    const yamlRegex = /^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/;
    const match = content.match(yamlRegex);
    if (match) {
      try {
        const yaml = (0, import_obsidian2.parseYaml)(match[1]);
        return {
          yaml: yaml || {},
          body: match[2]
        };
      } catch (error) {
        console.error("Failed to parse YAML:", error);
        return {
          yaml: {},
          body: content
        };
      }
    }
    return {
      yaml: {},
      body: content
    };
  }
  /**
   * Merge existing YAML metadata with new AI-generated metadata
   */
  static mergeMetadata(existing, newMetadata) {
    const merged = { ...existing };
    Object.keys(newMetadata).forEach((key) => {
      const newValue = newMetadata[key];
      const existingValue = merged[key];
      if (Array.isArray(newValue)) {
        const arrExisting = Array.isArray(existingValue) ? existingValue : [];
        const mergedArr = [.../* @__PURE__ */ new Set([...arrExisting, ...newValue])];
        if (mergedArr.length > 0) {
          merged[key] = mergedArr;
        }
      } else if (typeof newValue === "string" && newValue.length > 50) {
        if (!existingValue || newValue.length > (existingValue.length || 0)) {
          merged[key] = newValue;
        }
      } else if (newValue !== null && newValue !== void 0 && newValue !== "") {
        merged[key] = newValue;
      }
    });
    return merged;
  }
  /**
   * Format metadata as YAML frontmatter string
   */
  static formatFrontmatter(metadata) {
    if (!metadata || Object.keys(metadata).length === 0) {
      return "";
    }
    const yamlString = (0, import_obsidian2.stringifyYaml)(metadata);
    return `---
${yamlString.trim()}
---`;
  }
  /**
   * Insert or update YAML frontmatter in document content
   */
  static insertOrUpdateFrontmatter(content, metadata) {
    if (!metadata || Object.keys(metadata).length === 0) {
      return content;
    }
    const yamlString = this.formatFrontmatter(metadata);
    const { yaml, body } = this.parseFrontmatter(content);
    if (yaml && Object.keys(yaml).length > 0) {
      return `${yamlString}
${body}`;
    } else {
      return `${yamlString}
${content}`;
    }
  }
  /**
   * Extract content without YAML frontmatter for AI analysis
   */
  static getContentWithoutFrontmatter(content) {
    const { body } = this.parseFrontmatter(content);
    return body.trim();
  }
  /**
   * Check if document has valid YAML frontmatter
   */
  static hasFrontmatter(content) {
    return /^---\s*\n/.test(content);
  }
};

// src/ui/metadata-modal.ts
var import_obsidian3 = require("obsidian");
var MetadataModal = class extends import_obsidian3.Modal {
  constructor(app, initialMetadata, fields, onSubmit) {
    super(app);
    this.initialMetadata = initialMetadata;
    this.fields = fields;
    this.onSubmit = onSubmit;
    this.metadata = { ...initialMetadata };
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u786E\u8BA4\u5143\u6570\u636E (Confirm Metadata)" });
    const arrayToString = (arr) => Array.isArray(arr) ? arr.join(", ") : arr || "";
    const stringToArray = (str) => str.split(/[,，]/).map((s) => s.trim()).filter((s) => s.length > 0);
    this.fields.forEach((field) => {
      if (!field.enabled)
        return;
      if (field.type === "string" && field.key === "summary") {
        new import_obsidian3.Setting(contentEl).setName(field.label).setDesc(field.description || "").addTextArea((text) => {
          var _a;
          return text.setValue(((_a = this.metadata[field.key]) == null ? void 0 : _a.toString()) || "").onChange((value) => {
            this.metadata[field.key] = value;
          });
        });
      } else if (field.type === "string") {
        new import_obsidian3.Setting(contentEl).setName(field.label).setDesc(field.description || "").addText((text) => {
          var _a;
          return text.setValue(((_a = this.metadata[field.key]) == null ? void 0 : _a.toString()) || "").onChange((value) => {
            this.metadata[field.key] = value;
          });
        });
      } else if (field.type === "array") {
        new import_obsidian3.Setting(contentEl).setName(field.label).setDesc(field.description || "\u9017\u53F7\u5206\u9694").addText((text) => text.setValue(arrayToString(this.metadata[field.key])).onChange((value) => {
          this.metadata[field.key] = stringToArray(value);
        }));
      } else if (field.type === "select") {
        new import_obsidian3.Setting(contentEl).setName(field.label).setDesc(field.description || "").addDropdown((drop) => {
          var _a, _b;
          (_a = field.options) == null ? void 0 : _a.forEach((opt) => drop.addOption(opt, opt));
          return drop.setValue(this.metadata[field.key] || ((_b = field.options) == null ? void 0 : _b[0]) || "").onChange((value) => {
            this.metadata[field.key] = value;
          });
        });
      }
    });
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("\u786E\u8BA4\u5E76\u4FDD\u5B58").setCta().onClick(() => {
      this.close();
      this.onSubmit(this.metadata);
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/field-edit-modal.ts
var import_obsidian4 = require("obsidian");
var FieldEditModal = class extends import_obsidian4.Modal {
  constructor(app, field, onSubmit) {
    super(app);
    this.field = { ...field };
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u7F16\u8F91\u5B57\u6BB5" });
    new import_obsidian4.Setting(contentEl).setName("YAML Key").setDesc("\u5728frontmatter\u4E2D\u4F7F\u7528\u7684\u5C5E\u6027\u540D").addText((text) => text.setValue(this.field.key).onChange((value) => this.field.key = value));
    new import_obsidian4.Setting(contentEl).setName("\u663E\u793A\u6807\u7B7E").setDesc("UI\u663E\u793A\u7684\u540D\u79F0").addText((text) => text.setValue(this.field.label).onChange((value) => this.field.label = value));
    new import_obsidian4.Setting(contentEl).setName("\u63D0\u793A\u63CF\u8FF0").setDesc("\u544A\u8BC9AI\u5982\u4F55\u751F\u6210\u8FD9\u4E2A\u5B57\u6BB5").addTextArea((text) => text.setValue(this.field.description || "").onChange((value) => this.field.description = value));
    new import_obsidian4.Setting(contentEl).setName("\u7C7B\u578B").addDropdown((drop) => drop.addOption("string", "\u6587\u672C (String)").addOption("array", "\u5217\u8868 (Array)").addOption("select", "\u9009\u62E9 (Select)").setValue(this.field.type).onChange((value) => {
      this.field.type = value;
      this.displayOptionsInput(optionsSettingContainer);
    }));
    const optionsSettingContainer = contentEl.createDiv();
    this.displayOptionsInput(optionsSettingContainer);
    new import_obsidian4.Setting(contentEl).addButton((btn) => btn.setButtonText("\u4FDD\u5B58").setCta().onClick(() => {
      this.close();
      this.onSubmit(this.field);
    }));
  }
  displayOptionsInput(container) {
    container.empty();
    if (this.field.type === "select") {
      new import_obsidian4.Setting(container).setName("\u9009\u9879").setDesc("\u7528\u9017\u53F7\u5206\u9694\u7684\u9009\u9879").addTextArea((text) => {
        var _a;
        return text.setValue(((_a = this.field.options) == null ? void 0 : _a.join(",")) || "").onChange((value) => {
          this.field.options = value.split(/[,，]/).map((s) => s.trim()).filter((s) => s.length > 0);
        });
      });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/types/index.ts
var DEFAULT_FIELDS = [
  { key: "tags", label: "\u6807\u7B7E (tags)", description: "3-5\u4E2A\u76F8\u5173\u6807\u7B7E\uFF08\u82F1\u6587\uFF0C\u5C0F\u5199\uFF0C\u7528\u8FDE\u5B57\u7B26\u8FDE\u63A5\uFF09", type: "array", enabled: true },
  { key: "summary", label: "\u6458\u8981 (summary)", description: "\u75281-2\u53E5\u8BDD\u7B80\u6D01\u603B\u7ED3\u6587\u6863\u4E3B\u8981\u5185\u5BB9\uFF08\u4E2D\u6587\uFF09", type: "string", enabled: true },
  { key: "categories", label: "\u5206\u7C7B (categories)", description: "1-2\u4E2A\u6587\u6863\u6240\u5C5E\u5206\u7C7B\uFF08\u4E2D\u6587\uFF09", type: "array", enabled: true },
  { key: "keywords", label: "\u5173\u952E\u8BCD (keywords)", description: "3-5\u4E2A\u5173\u952E\u8BCD\uFF08\u4E2D\u6587\uFF09", type: "array", enabled: true },
  { key: "status", label: "\u72B6\u6001 (status)", description: "\u6587\u6863\u72B6\u6001", type: "select", options: ["\u8349\u7A3F", "\u8FDB\u884C\u4E2D", "\u5DF2\u5B8C\u6210", "\u5F52\u6863"], enabled: true },
  { key: "priority", label: "\u4F18\u5148\u7EA7 (priority)", description: "\u4F18\u5148\u7EA7", type: "select", options: ["\u4F4E", "\u4E2D", "\u9AD8"], enabled: true }
];
var DEFAULT_SETTINGS = {
  // AI Provider
  provider: "openai",
  // OpenAI Settings
  openaiApiKey: "",
  openaiBaseURL: "https://api.openai.com/v1",
  openaiModel: "gpt-3.5-turbo",
  // Anthropic Settings
  anthropicApiKey: "",
  anthropicModel: "claude-3-sonnet-20240229",
  // Custom Provider Settings
  customApiKey: "",
  customBaseURL: "",
  customModel: "",
  // Common Settings
  maxTokens: 1e3,
  temperature: 0.7,
  // Field Configuration
  fields: DEFAULT_FIELDS,
  // Auto Analyze
  autoAnalyze: false
};

// src/main.ts
var DocumentAnalyzerPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.analyzer = null;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("sparkles", "AI\u5206\u6790\u6587\u6863", () => {
      this.analyzeCurrentDocument();
    });
    this.addCommand({
      id: "analyze-document-with-ai",
      name: "AI\u5206\u6790\u5F53\u524D\u6587\u6863\u5E76\u751F\u6210YAML\u5143\u6570\u636E",
      callback: () => {
        this.analyzeCurrentDocument();
      }
    });
    this.addSettingTab(new DocumentAnalyzerSettingTab(this.app, this));
    console.log("Document AI Analyzer plugin loaded");
  }
  onunload() {
    console.log("Document AI Analyzer plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Get the API config based on selected provider
   */
  getAIConfig() {
    const provider = this.settings.provider;
    if (provider === "openai") {
      return {
        apiKey: this.settings.openaiApiKey,
        provider,
        baseURL: this.settings.openaiBaseURL,
        model: this.settings.openaiModel,
        maxTokens: this.settings.maxTokens
      };
    } else if (provider === "anthropic") {
      return {
        apiKey: this.settings.anthropicApiKey,
        provider,
        baseURL: "https://api.anthropic.com/v1",
        model: this.settings.anthropicModel,
        maxTokens: this.settings.maxTokens
      };
    } else {
      return {
        apiKey: this.settings.customApiKey,
        provider,
        baseURL: this.settings.customBaseURL,
        model: this.settings.customModel,
        maxTokens: this.settings.maxTokens
      };
    }
  }
  /**
   * Analyze the current active document
   */
  async analyzeCurrentDocument() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (!activeView) {
      new import_obsidian5.Notice("\u274C \u8BF7\u5148\u6253\u5F00\u4E00\u4E2AMarkdown\u6587\u6863");
      return;
    }
    const editor = activeView.editor;
    const content = editor.getValue();
    if (!content || content.trim().length < 50) {
      new import_obsidian5.Notice("\u274C \u6587\u6863\u5185\u5BB9\u592A\u77ED\uFF0C\u65E0\u6CD5\u5206\u6790\uFF08\u81F3\u5C11\u9700\u898150\u4E2A\u5B57\u7B26\uFF09");
      return;
    }
    const config = this.getAIConfig();
    if (!config.apiKey) {
      new import_obsidian5.Notice("\u274C \u8BF7\u5148\u5728\u63D2\u4EF6\u8BBE\u7F6E\u4E2D\u914D\u7F6EAPI\u5BC6\u94A5");
      return;
    }
    const loadingNotice = new import_obsidian5.Notice("\u{1F916} AI\u6B63\u5728\u5206\u6790\u6587\u6863...", 0);
    try {
      const aiService = new AIService(config);
      this.analyzer = new DocumentAnalyzer(aiService, this.settings);
      const contentForAnalysis = YamlHelper.getContentWithoutFrontmatter(content);
      const result = await this.analyzer.analyze(contentForAnalysis);
      loadingNotice.hide();
      if (!result.success) {
        new import_obsidian5.Notice(`\u274C ${result.error}`);
        return;
      }
      if (!result.metadata) {
        new import_obsidian5.Notice("\u274C AI\u672A\u80FD\u751F\u6210\u5143\u6570\u636E");
        return;
      }
      const { yaml: existingYaml } = YamlHelper.parseFrontmatter(content);
      const mergedMetadata = YamlHelper.mergeMetadata(existingYaml || {}, result.metadata);
      new MetadataModal(this.app, mergedMetadata, this.settings.fields, (finalMetadata) => {
        const newContent = YamlHelper.insertOrUpdateFrontmatter(content, finalMetadata);
        editor.setValue(newContent);
        new import_obsidian5.Notice("\u2705 \u5DF2\u66F4\u65B0\u6587\u6863\u5143\u6570\u636E");
      }).open();
    } catch (error) {
      console.error("Document analysis failed:", error);
      loadingNotice.hide();
      new import_obsidian5.Notice(`\u274C \u5206\u6790\u5931\u8D25: ${error.message}`);
    }
  }
};
var DocumentAnalyzerSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Document AI Analyzer \u8BBE\u7F6E" });
    containerEl.createEl("h3", { text: "\u{1F916} AI \u63D0\u4F9B\u5546" });
    new import_obsidian5.Setting(containerEl).setName("AI \u63D0\u4F9B\u5546").setDesc("\u9009\u62E9AI\u670D\u52A1\u63D0\u4F9B\u5546").addDropdown(
      (dropdown) => dropdown.addOption("openai", "OpenAI").addOption("anthropic", "Anthropic (Claude)").addOption("custom", "\u81EA\u5B9A\u4E49").setValue(this.plugin.settings.provider).onChange(async (value) => {
        this.plugin.settings.provider = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.provider === "openai") {
      containerEl.createEl("h3", { text: "OpenAI \u914D\u7F6E" });
      new import_obsidian5.Setting(containerEl).setName("OpenAI API \u5BC6\u94A5").setDesc("\u4F60\u7684OpenAI API\u5BC6\u94A5\uFF08\u4EE5sk-\u5F00\u5934\uFF09").addText(
        (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
          this.plugin.settings.openaiApiKey = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian5.Setting(containerEl).setName("API Base URL").setDesc("OpenAI API\u7684\u57FA\u7840URL\uFF08\u9ED8\u8BA4\u4F7F\u7528\u5B98\u65B9\u5730\u5740\uFF09").addText(
        (text) => text.setPlaceholder("https://api.openai.com/v1").setValue(this.plugin.settings.openaiBaseURL).onChange(async (value) => {
          this.plugin.settings.openaiBaseURL = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian5.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u4F7F\u7528\u7684OpenAI\u6A21\u578B").addText(
        (text) => text.setPlaceholder("gpt-3.5-turbo").setValue(this.plugin.settings.openaiModel).onChange(async (value) => {
          this.plugin.settings.openaiModel = value;
          await this.plugin.saveSettings();
        })
      );
    }
    if (this.plugin.settings.provider === "anthropic") {
      containerEl.createEl("h3", { text: "Anthropic \u914D\u7F6E" });
      new import_obsidian5.Setting(containerEl).setName("Anthropic API \u5BC6\u94A5").setDesc("\u4F60\u7684Anthropic API\u5BC6\u94A5").addText(
        (text) => text.setPlaceholder("sk-ant-...").setValue(this.plugin.settings.anthropicApiKey).onChange(async (value) => {
          this.plugin.settings.anthropicApiKey = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian5.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u4F7F\u7528\u7684Claude\u6A21\u578B").addText(
        (text) => text.setPlaceholder("claude-3-sonnet-20240229").setValue(this.plugin.settings.anthropicModel).onChange(async (value) => {
          this.plugin.settings.anthropicModel = value;
          await this.plugin.saveSettings();
        })
      );
    }
    if (this.plugin.settings.provider === "custom") {
      containerEl.createEl("h3", { text: "\u81EA\u5B9A\u4E49\u63D0\u4F9B\u5546\u914D\u7F6E" });
      new import_obsidian5.Setting(containerEl).setName("API \u5BC6\u94A5").setDesc("\u81EA\u5B9A\u4E49API\u5BC6\u94A5").addText(
        (text) => text.setPlaceholder("\u4F60\u7684API\u5BC6\u94A5").setValue(this.plugin.settings.customApiKey).onChange(async (value) => {
          this.plugin.settings.customApiKey = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian5.Setting(containerEl).setName("API Base URL").setDesc("\u81EA\u5B9A\u4E49API\u57FA\u7840URL").addText(
        (text) => text.setPlaceholder("https://your-api.com/v1").setValue(this.plugin.settings.customBaseURL).onChange(async (value) => {
          this.plugin.settings.customBaseURL = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian5.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u4F7F\u7528\u7684\u6A21\u578B\u540D\u79F0").addText(
        (text) => text.setPlaceholder("model-name").setValue(this.plugin.settings.customModel).onChange(async (value) => {
          this.plugin.settings.customModel = value;
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("h3", { text: "\u2699\uFE0F \u901A\u7528\u8BBE\u7F6E" });
    new import_obsidian5.Setting(containerEl).setName("\u6700\u5927Token\u6570").setDesc("AI\u54CD\u5E94\u7684\u6700\u5927token\u6570").addText(
      (text) => text.setPlaceholder("1000").setValue(this.plugin.settings.maxTokens.toString()).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num)) {
          this.plugin.settings.maxTokens = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Temperature").setDesc("AI\u751F\u6210\u7684\u968F\u673A\u6027\uFF080-1\uFF0C\u8D8A\u9AD8\u8D8A\u968F\u673A\uFF09").addSlider(
      (slider) => slider.setLimits(0, 1, 0.1).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.temperature = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F4CB} YAML \u5B57\u6BB5\u914D\u7F6E" });
    new import_obsidian5.Setting(containerEl).setName("\u6DFB\u52A0\u65B0\u5B57\u6BB5").setDesc("\u6DFB\u52A0\u4E00\u4E2A\u65B0\u7684YAML\u5B57\u6BB5").addButton(
      (button) => button.setButtonText("\u6DFB\u52A0\u5B57\u6BB5").setCta().onClick(async () => {
        this.plugin.settings.fields.push({
          key: "new-field",
          label: "\u65B0\u5B57\u6BB5",
          description: "\u5B57\u6BB5\u63CF\u8FF0",
          type: "string",
          enabled: true
        });
        await this.plugin.saveSettings();
        this.display();
      })
    );
    this.plugin.settings.fields.forEach((field, index) => {
      const fieldSetting = new import_obsidian5.Setting(containerEl);
      fieldSetting.setName(`${field.label} (${field.key})`).setDesc(field.description || "").addToggle(
        (toggle) => toggle.setValue(field.enabled).setTooltip("\u542F\u7528/\u7981\u7528").onChange(async (value) => {
          field.enabled = value;
          await this.plugin.saveSettings();
        })
      ).addExtraButton(
        (btn) => btn.setIcon("pencil").setTooltip("\u7F16\u8F91").onClick(() => {
          new FieldEditModal(this.plugin.app, field, async (updatedField) => {
            this.plugin.settings.fields[index] = updatedField;
            await this.plugin.saveSettings();
            this.display();
          }).open();
        })
      ).addExtraButton(
        (btn) => btn.setIcon("trash").setTooltip("\u5220\u9664").onClick(async () => {
          this.plugin.settings.fields.splice(index, 1);
          await this.plugin.saveSettings();
          this.display();
        })
      );
    });
    containerEl.createEl("div", {
      attr: {
        style: "margin-top: 2rem; padding: 1rem; background: var(--background-secondary); border-radius: 8px;"
      }
    }).createEl("p", {
      text: "\u{1F4A1} \u63D0\u793A\uFF1A\u914D\u7F6E\u5B8C\u6210\u540E\uFF0C\u70B9\u51FB\u5DE5\u5177\u680F\u7684\u2728\u56FE\u6807\u6216\u4F7F\u7528\u547D\u4EE4\u9762\u677F\u6765\u5206\u6790\u6587\u6863\u3002"
    });
  }
};
